name: library_arch_mvvm_modify_infinite_list
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.0

dependencies:
  library_architecture_mvvm_modify:
    path: ../../packages/library_architecture_mvvm_modify
  flutter:
    sdk: flutter
  meta: ^1.8.0
  cupertino_icons: ^1.0.2
  http: ^0.13.0

dev_dependencies:
  test: ^1.21.4
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
