name: library_arch_mvvm_modify_infinite_list
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  library_architecture_mvvm_modify:
    path: ../../packages/library_architecture_mvvm_modify
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
