import 'package:library_arch_mvvm_modify_infinite_list/model/postForInfiniteListWithoutDatabase/PostForInfiniteListWithoutDatabase.dart';
import 'package:library_architecture_mvvm_modify/base_model_named_database/base_list_model_named_database.dart';

class ListPostForInfiniteListWithoutDatabase
    extends BaseListModelNamedDatabase<PostForInfiniteListWithoutDatabase>
{
  ListPostForInfiniteListWithoutDatabase(List<PostForInfiniteListWithoutDatabase> listModelNamedDatabase) : super(listModelNamedDatabase);
}