name: library_architecture_mvvm_modify_todo
description: A new Flutter project.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.10.0

dependencies:
  library_architecture_mvvm_modify:
    path: ../
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  meta: ^1.8.0
  uuid: ^3.0.6
  rxdart: ^0.27.7
  sqflite: ^2.2.3
  cupertino_icons: ^1.0.2
  path: ^1.8.2

dev_dependencies:
  test: ^1.21.4
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
