name: example
description: A new Flutter project.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  library_architecture_mvvm_modify:
    path: ../
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.1
