name: example
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  library_architecture_mvvm_modify:
    path: ../
  meta: ^1.10.0
  http: ^1.1.0

dev_dependencies:
  lints: ^3.0.0
