name: library_architecture_mvvm_modify
description: MVVM Modification
version: 0.0.1
issue_tracker: https://github.com/JacobOdd/library_architecture_mvvm_modify/issues
homepage: https://github.com/JacobOdd/library_architecture_mvvm_modify
documentation: https://github.com/JacobOdd/library_architecture_mvvm_modify/blob/main/README.md#documentation

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  sqflite: ^2.0.0
  shared_preferences: ^2.0.8
  path: ^1.8.0
  path_provider: ^2.0.0
  ansicolor: ^2.0.1
  equatable: ^2.0.5
  meta: ^1.3.0

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.18.2
  flutter_lints: ^1.0.0

