import 'package:library_arch_mvvm_modify_firebase_login/utility/customDataSource/DefaultFirebaseAuthAndGoogleSignInDataSource.dart';

class UserFirebaseAuthAndGoogleSignInDataSource
    extends DefaultFirebaseAuthAndGoogleSignInDataSource
{

}