import 'package:library_arch_mvvm_modify_counter/modelQNamedServiceViewModel/intQNoServiceViewModel/IntQNoServiceViewModelUsingGetNPForIncrementAndDecrement.dart';
import 'package:library_arch_mvvm_modify_counter/utility/modelQNamedServiceListViewModelForNamedWidget/IntQNoServiceListViewModelForDecrementFABWidget.dart';
import 'package:library_arch_mvvm_modify_counter/utility/modelQNamedServiceListViewModelForNamedWidget/IntQNoServiceListViewModelForIncrementFABWidget.dart';
import 'package:library_arch_mvvm_modify_counter/utility/modelQNamedServiceListViewModelForNamedWidget/IntQNoServiceListViewModelForIntTextWidget.dart';
import 'package:library_architecture_mvvm_modify/base_named_view_list_view_model/base_named_view_list_view_model.dart';

class MainViewListViewModel
    extends BaseNamedViewListViewModel
{
  // ModelQNamedServiceViewModel
  final _intQNoServiceViewModelUsingGetNPForIncrementAndDecrement =
  IntQNoServiceViewModelUsingGetNPForIncrementAndDecrement();

  // ModelQNamedServiceListViewModelForNamedWidget
  IntQNoServiceListViewModelForIntTextWidget intQNoServiceListViewModelForIntTextWidget;
  IntQNoServiceListViewModelForIncrementFABWidget intQNoServiceListViewModelForIncrementFABWidget;
  IntQNoServiceListViewModelForDecrementFABWidget intQNoServiceListViewModelForDecrementFABWidget;

  MainViewListViewModel()  {
    intQNoServiceListViewModelForIntTextWidget = IntQNoServiceListViewModelForIntTextWidget(_intQNoServiceViewModelUsingGetNPForIncrementAndDecrement);
    intQNoServiceListViewModelForIncrementFABWidget = IntQNoServiceListViewModelForIncrementFABWidget(_intQNoServiceViewModelUsingGetNPForIncrementAndDecrement);
    intQNoServiceListViewModelForDecrementFABWidget = IntQNoServiceListViewModelForDecrementFABWidget(_intQNoServiceViewModelUsingGetNPForIncrementAndDecrement);
  }

  @override
  void dispose() {
    _intQNoServiceViewModelUsingGetNPForIncrementAndDecrement.dispose();
  }
}