import 'package:library_arch_mvvm_modify_github_search/model/customTimer/CustomTimer.dart';
import 'package:library_arch_mvvm_modify_github_search/model/customTimer/ListCustomTimer.dart';
import 'package:library_arch_mvvm_modify_github_search/model/customTimer/cloneStreamCustomTimerForSuccess/CloneStreamCustomTimerForSuccess.dart';
import 'package:library_arch_mvvm_modify_github_search/model/searchResult/ListSearchResult.dart';
import 'package:library_arch_mvvm_modify_github_search/model/searchResult/SearchResult.dart';
import 'package:library_arch_mvvm_modify_github_search/model/searchResult/cloneStreamSearchResultForSuccess/CloneStreamSearchResultForSuccess.dart';
import 'package:library_arch_mvvm_modify_github_search/model/searchResult/searchResultForNamed/ListSearchResultForLocalExceptionTIP.dart';
import 'package:library_arch_mvvm_modify_github_search/model/searchResult/searchResultForNamed/ListSearchResultForMapTIP.dart';
import 'package:library_arch_mvvm_modify_github_search/model/searchResult/searchResultForNamed/ListSearchResultForNetworkExceptionTIP.dart';
import 'package:library_arch_mvvm_modify_github_search/model/searchResult/searchResultForNamed/ListSearchResultForObjectTIP.dart';
import 'package:library_arch_mvvm_modify_github_search/model/searchResultInLoading/ListSearchResultInLoading.dart';
import 'package:library_arch_mvvm_modify_github_search/model/searchResultInLoading/SearchResultInLoading.dart';
import 'package:library_arch_mvvm_modify_github_search/model/searchResultInLoading/cloneStreamSearchResultInLoadingForSuccess/CloneStreamSearchResultInLoadingForSuccess.dart';
import 'package:library_arch_mvvm_modify_github_search/modelQNamedServiceViewModel/boolQNoServiceViewModel/BoolQNoServiceViewModelUsingGetNPForAntiSpam.dart';
import 'package:library_arch_mvvm_modify_github_search/modelQNamedServiceViewModel/customTimerQNoServiceViewModel/CustomTimerQNoServiceViewModelUsingGetNP.dart';
import 'package:library_arch_mvvm_modify_github_search/modelQNamedServiceViewModel/searchResultInLoadingQNoServiceViewModel/SearchResultInLoadingQNoServiceViewModelUsingGetListNP.dart';
import 'package:library_arch_mvvm_modify_github_search/modelQNamedServiceViewModel/searchResultQGithubCacheAndHttpClientServiceViewModel/SearchResultQGithubCacheAndHttpClientServiceViewModelUsingGetListParameterStringForSearchFromApiGithub.dart';
import 'package:library_arch_mvvm_modify_github_search/modelQNamedServiceViewModel/stringsQNoServiceViewModel/StringsQNoServiceViewModelUsingGetNPForSaveLettersSearch.dart';
import 'package:library_arch_mvvm_modify_github_search/namedViewListViewModel/namedWidgetListViewModel/SearchBarWidgetListViewModel.dart';
import 'package:library_arch_mvvm_modify_github_search/namedViewListViewModel/namedWidgetListViewModel/SearchBodyWidgetListViewModel.dart';
import 'package:library_architecture_mvvm_modify/base_model/bool.dart';
import 'package:library_architecture_mvvm_modify/base_model/interface_clone_stream_model_for_success/stream_bool_for_success.dart';
import 'package:library_architecture_mvvm_modify/base_model/interface_clone_stream_model_for_success/stream_strings_for_success.dart';
import 'package:library_architecture_mvvm_modify/base_model/list_bool.dart';
import 'package:library_architecture_mvvm_modify/base_model/list_strings.dart';
import 'package:library_architecture_mvvm_modify/base_model/strings.dart';
import 'package:library_architecture_mvvm_modify/base_named_view_list_view_model/base_named_view_list_view_model.dart';

class MainViewListViewModel
    extends BaseNamedViewListViewModel
{
  // ModelQNamedServiceViewModel
  final _searchResultQGithubCacheAndHttpClientServiceViewModelUsingGetListParameterStringForSearchFromApiGithub = SearchResultQGithubCacheAndHttpClientServiceViewModelUsingGetListParameterStringForSearchFromApiGithub<SearchResult,ListSearchResult<SearchResult>>(CloneStreamSearchResultForSuccess(),ListSearchResultForMapTIP(),ListSearchResultForNetworkExceptionTIP(),ListSearchResultForLocalExceptionTIP(),ListSearchResultForObjectTIP());
  final _boolQNoServiceViewModelUsingGetNPForAntiSpam = BoolQNoServiceViewModelUsingGetNPForAntiSpam<Bool,ListBool<Bool>>(StreamBoolForSuccess());
  final _stringsQNoServiceViewModelUsingGetNPForSaveLettersSearch = StringsQNoServiceViewModelUsingGetNPForSaveLettersSearch<Strings,ListStrings<Strings>>(StreamStringsForSuccess());
  final _searchResultInLoadingQNoServiceViewModelUsingGetListNP = SearchResultInLoadingQNoServiceViewModelUsingGetListNP<SearchResultInLoading,ListSearchResultInLoading<SearchResultInLoading>>(CloneStreamSearchResultInLoadingForSuccess());
  final _customTimerQNoServiceViewModelUsingGetNP = CustomTimerQNoServiceViewModelUsingGetNP<CustomTimer,ListCustomTimer<CustomTimer>>(CloneStreamCustomTimerForSuccess());

  // NamedWidgetListViewModel
  late final SearchBarWidgetListViewModel searchBarWidgetListViewModel;
  late final SearchBodyWidgetListViewModel searchBodyWidgetListViewModel;

  MainViewListViewModel() {
    searchBarWidgetListViewModel = SearchBarWidgetListViewModel(_searchResultQGithubCacheAndHttpClientServiceViewModelUsingGetListParameterStringForSearchFromApiGithub, _boolQNoServiceViewModelUsingGetNPForAntiSpam, _stringsQNoServiceViewModelUsingGetNPForSaveLettersSearch, _searchResultInLoadingQNoServiceViewModelUsingGetListNP, _customTimerQNoServiceViewModelUsingGetNP);
    searchBodyWidgetListViewModel = SearchBodyWidgetListViewModel(_searchResultInLoadingQNoServiceViewModelUsingGetListNP);
  }

  @override
  void dispose() {
    _searchResultQGithubCacheAndHttpClientServiceViewModelUsingGetListParameterStringForSearchFromApiGithub.dispose();
    _boolQNoServiceViewModelUsingGetNPForAntiSpam.dispose();
    _stringsQNoServiceViewModelUsingGetNPForSaveLettersSearch.dispose();
    _searchResultInLoadingQNoServiceViewModelUsingGetListNP.dispose();
    _customTimerQNoServiceViewModelUsingGetNP.dispose();
  }
}