import 'package:firebase_auth/firebase_auth.dart';
import 'package:library_arch_mvvm_modify_firebase_login/modelNamed/userFirebaseAuthAndTempCache/UserFirebaseAuthAndTempCache.dart';
import 'package:library_arch_mvvm_modify_firebase_login/modelNamedBackgroundModel/UserFirebaseAuthAndTempCacheBackgroundModel.dart';
import 'package:library_arch_mvvm_modify_firebase_login/modelNamedDataSource/userFirebaseAuthAndTempCacheDataSource/UserFirebaseAuthAndTempCacheDataSourceUsingCustomStreamForCheckAuthAndSaveToTempCache.dart';
import 'package:library_arch_mvvm_modify_firebase_login/utility/TempCache.dart';

class UserFirebaseAuthAndTempCacheBackgroundModelUsingCustomStreamForCheckAuthAndSaveToTempCache
    extends UserFirebaseAuthAndTempCacheBackgroundModel
{
  UserFirebaseAuthAndTempCacheBackgroundModelUsingCustomStreamForCheckAuthAndSaveToTempCache(FirebaseAuth firebaseAuth,TempCache tempCache) : super.thereIsDataSource(UserFirebaseAuthAndTempCacheDataSourceUsingCustomStreamForCheckAuthAndSaveToTempCache(firebaseAuth,tempCache));

  @override
  Object thisClass() {
    return this;
  }

  Stream<UserFirebaseAuthAndTempCache> get getCustomStreamUserFirebaseAuthAndTempCache {
    return getDataSource<UserFirebaseAuthAndTempCacheDataSourceUsingCustomStreamForCheckAuthAndSaveToTempCache>().getCustomStreamUserFirebaseAuthAndTempCache;
  }
}