
import 'package:library_architecture_mvvm_modify/function_view_model/interface_function_view_model/insert_model_fvm/insert_model_to_local_database_there_is_parameter_fvm.dart';
import 'package:library_architecture_mvvm_modify/function_view_model/interface_function_view_model/insert_model_fvm/insert_model_to_network_database_there_is_parameter_fvm.dart';

abstract class InsertModelToLNDatabaseThereIsParameterFVM
    implements
        InsertModelToLocalDatabaseThereIsParameterFVM,
        InsertModelToNetworkDatabaseThereIsParameterFVM {
}