name: library_arch_mvvm_modify_weather
description: A new Flutter project.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.10.0

dependencies:
  library_architecture_mvvm_modify:
    path: ../../packages/library_architecture_mvvm_modify
  flutter:
    sdk: flutter
  meta: ^1.8.0
  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_fonts: ^3.0.1
  json_annotation: ^4.7.0
  path_provider: ^2.0.8
  http: ^0.13.0

dev_dependencies:
  test: ^1.21.4
  flutter_lints: ^2.0.0
  json_serializable: ^6.0.0
  build_runner: ^2.0.0

flutter:
  uses-material-design: true