import 'package:library_arch_mvvm_modify_github_search/model/searchResultInLoading/ListSearchResultInLoading.dart';
import 'package:library_arch_mvvm_modify_github_search/model/searchResultInLoading/SearchResultInLoading.dart';
import 'package:library_arch_mvvm_modify_github_search/modelQThereIsStateViewModel/searchResultInLoadingQThereIsStateViewModel/SearchResultInLoadingQThereIsStateViewModel.dart';
import 'package:meta/meta.dart';

class SearchBodyWidgetListViewModel {
  @protected
  final SearchResultInLoadingQThereIsStateViewModel<SearchResultInLoading,ListSearchResultInLoading<SearchResultInLoading>> searchResultInLoadingQThereIsStateViewModel;

  SearchBodyWidgetListViewModel(this.searchResultInLoadingQThereIsStateViewModel);

  Stream<ListSearchResultInLoading<SearchResultInLoading>>? get getStreamListSearchResultInLoading {
    return searchResultInLoadingQThereIsStateViewModel.getStreamListSearchResultInLoading;
  }
}