import 'package:library_arch_mvvm_modify_infinite_list/modelQNamedServiceViewModel/boolQNoServiceViewModel/BoolQNoServiceViewModelUsingGetNPForAntiSpam.dart';
import 'package:library_arch_mvvm_modify_infinite_list/modelQNamedServiceViewModel/postQHttpClientServiceViewModel/PostQHttpClientServiceViewModelUsingGetListParameterIntForStartIndexFromJsonPlaceholder.dart';
import 'package:library_arch_mvvm_modify_infinite_list/utility/modelQNamedServiceListViewModelForNamedWidget/PostQHttpClientServiceAndBoolQNoServiceListViewModelForPostsListWidget.dart';
import 'package:library_arch_mvvm_modify_infinite_list/utility/modelQNamedServiceListViewModelForNamedWidget/PostQHttpClientServiceAndBoolQNoServiceListViewModelForPostsListWidgetTwo.dart';
import 'package:library_architecture_mvvm_modify/base_named_view_list_view_model/base_named_view_list_view_model.dart';

class MainViewListViewModel
    extends BaseNamedViewListViewModel
{
  // ModelQNamedServiceViewModel
  final _postQHttpClientServiceViewModelUsingGetListParameterIntForStartIndexFromJsonPlaceholder =
  PostQHttpClientServiceViewModelUsingGetListParameterIntForStartIndexFromJsonPlaceholder();
  final _boolQNoServiceViewModelUsingGetNPForAntiSpam =
  BoolQNoServiceViewModelUsingGetNPForAntiSpam();

  // ModelQNamedServiceListViewModelForNamedWidget
  late final PostQHttpClientServiceAndBoolQNoServiceListViewModelForPostsListWidget postQHttpClientServiceAndBoolQNoServiceListViewModelForPostsListWidget;
  late final PostQHttpClientServiceAndBoolQNoServiceListViewModelForPostsListWidgetTwo postQHttpClientServiceAndBoolQNoServiceListViewModelForPostsListWidgetTwo;

  MainViewListViewModel() {
    postQHttpClientServiceAndBoolQNoServiceListViewModelForPostsListWidget = PostQHttpClientServiceAndBoolQNoServiceListViewModelForPostsListWidget(_postQHttpClientServiceViewModelUsingGetListParameterIntForStartIndexFromJsonPlaceholder, _boolQNoServiceViewModelUsingGetNPForAntiSpam);
    postQHttpClientServiceAndBoolQNoServiceListViewModelForPostsListWidgetTwo = PostQHttpClientServiceAndBoolQNoServiceListViewModelForPostsListWidgetTwo(postQHttpClientServiceAndBoolQNoServiceListViewModelForPostsListWidget);
  }

  @override
  void dispose() {
    _postQHttpClientServiceViewModelUsingGetListParameterIntForStartIndexFromJsonPlaceholder.dispose();
    _boolQNoServiceViewModelUsingGetNPForAntiSpam.dispose();
  }

 /* Future<void> getListPostFromJsonPlaceholderServiceParameterIntAndSetListPostAndInGeneralOneTask()
  async {
    // 1
    await _postQJsonPlaceholderServiceViewModelUsingGetListParameterIntForStartIndex
        .getListPostFromJsonPlaceholderServiceParameterIntAndSetListPost(IntTypeParameter(0));
    _postQJsonPlaceholderServiceViewModelUsingGetListParameterIntForStartIndex
        .notifyStreamListPostUsingGetListParameterIntForStartIndex();
    return;
  }*/
}