import 'package:library_arch_mvvm_modify_firebase_login/utility/customDataSource/DefaultFirebaseAuthAndTempCacheDataSource.dart';

class UserFirebaseAuthAndTempCacheDataSource
    extends DefaultFirebaseAuthAndTempCacheDataSource
{

}