

import 'package:library_architecture_mvvm_modify/function_view_model/interface_function_view_model/get_model_from_database_there_is_parameter_fvm/get_model_from_local_database_there_is_parameter_fvm.dart';
import 'package:library_architecture_mvvm_modify/function_view_model/interface_function_view_model/get_model_from_database_there_is_parameter_fvm/get_model_from_network_database_there_is_parameter_fvm.dart';

abstract class GetModelFromLNDatabaseThereIsParameterFVM
    implements
        GetModelFromLocalDatabaseThereIsParameterFVM,
        GetModelFromNetworkDatabaseThereIsParameterFVM {
}