/* START RESPONSE LOCAL/NETWORK ViewModel CONST */

const String CONST_SUCCESS = "SUCCESS";
/*const String CONST_LOCAL_NOT_OPERATION_INSERT_OR_UPDATE_OR_DELETE_OR_NOTIFICATION_FAILURE = "LOCAL_NOT_OPERATION_INSERT_OR_UPDATE_OR_DELETE_OR_NOTIFICATION_FAILURE";
const String CONST_NETWORK_NOT_OPERATION_INSERT_OR_UPDATE_OR_DELETE_FAILURE = "NETWORK_NOT_OPERATION_INSERT_OR_UPDATE_OR_DELETE_FAILURE";*/

/* END RESPONSE LOCAL/NETWORK ViewModel CONST */
