enum EnumBaseListModelDomainObjectOperationViewModel {
  getListModelFromLocalDatabaseThereIsParameterAndNoThereIsParameter,
  getListModelFromNetworkDatabaseThereIsParameterAndNoThereIsParameter,

  insertModelsToLocalDatabaseThereIsParameter,
  updateModelsToLocalDatabaseThereIsParameter,
  deleteModelsToLocalDatabaseThereIsParameter,

  insertModelsToNetworkDatabaseThereIsParameter,
  updateModelsToNetworkDatabaseThereIsParameter,
  deleteModelsToNetworkDatabaseThereIsParameter,
}