enum EnumBaseTypeParameterVM {
  getModelFromLocalDatabaseThereIsParameter,
  getModelFromNetworkDatabaseThereIsParameter,

  getListModelFromLocalDatabaseThereIsParameter,
  getListModelFromNetworkDatabaseThereIsParameter,

  getListModelFromLocalDatabaseThereIsParameterAndDeleteListModelToLocalDatabaseThereIsParameter,
  getListModelFromLocalDatabaseThereIsParameterAndDeleteListModelToNetworkDatabaseThereIsParameter,
  getListModelFromLocalDatabaseThereIsParameterAndInsertListModelToLocalDatabaseThereIsParameter,
  getListModelFromLocalDatabaseThereIsParameterAndInsertListModelToNetworkDatabaseThereIsParameter,
  getListModelFromLocalDatabaseThereIsParameterAndUpdateListModelToLocalDatabaseThereIsParameter,
  getListModelFromLocalDatabaseThereIsParameterAndUpdateListModelToNetworkDatabaseThereIsParameter,

  getListModelFromNetworkDatabaseThereIsParameterAndDeleteListModelToLocalDatabaseThereIsParameter,
  getListModelFromNetworkDatabaseThereIsParameterAndDeleteListModelToNetworkDatabaseThereIsParameter,
  getListModelFromNetworkDatabaseThereIsParameterAndInsertListModelToLocalDatabaseThereIsParameter,
  getListModelFromNetworkDatabaseThereIsParameterAndInsertListModelToNetworkDatabaseThereIsParameter,
  getListModelFromNetworkDatabaseThereIsParameterAndUpdateListModelToLocalDatabaseThereIsParameter,
  getListModelFromNetworkDatabaseThereIsParameterAndUpdateListModelToNetworkDatabaseThereIsParameter,

  getModelFromLocalDatabaseThereIsParameterAndDeleteModelToLocalDatabaseThereIsParameter,
  getModelFromLocalDatabaseThereIsParameterAndDeleteModelToNetworkDatabaseThereIsParameter,
  getModelFromLocalDatabaseThereIsParameterAndInsertModelToLocalDatabaseThereIsParameter,
  getModelFromLocalDatabaseThereIsParameterAndInsertModelToNetworkDatabaseThereIsParameter,
  getModelFromLocalDatabaseThereIsParameterAndUpdateModelToLocalDatabaseThereIsParameter,
  getModelFromLocalDatabaseThereIsParameterAndUpdateModelToNetworkDatabaseThereIsParameter,

  getModelFromNetworkDatabaseThereIsParameterAndDeleteModelToLocalDatabaseThereIsParameter,
  getModelFromNetworkDatabaseThereIsParameterAndDeleteModelToNetworkDatabaseThereIsParameter,
  getModelFromNetworkDatabaseThereIsParameterAndInsertModelToLocalDatabaseThereIsParameter,
  getModelFromNetworkDatabaseThereIsParameterAndInsertModelToNetworkDatabaseThereIsParameter,
  getModelFromNetworkDatabaseThereIsParameterAndUpdateModelToLocalDatabaseThereIsParameter,
  getModelFromNetworkDatabaseThereIsParameterAndUpdateModelToNetworkDatabaseThereIsParameter,
}