enum EnumBaseModelDomainObjectOperationViewModel {
  insertModelToLocalDatabaseForOneEntryThereIsParameter,
  getModelFromLocalDatabaseForOneEntryThereIsParameter,

  insertModelToLocalDatabaseThereIsParameter,
  updateModelToLocalDatabaseThereIsParameter,
  deleteModelToLocalDatabaseThereIsParameter,
  getModelFromLocalDatabaseThereIsParameter,

  insertModelToNetworkDatabaseThereIsParameter,
  updateModelToNetworkDatabaseThereIsParameter,
  deleteModelToNetworkDatabaseThereIsParameter,
  getModelFromNetworkDatabaseThereIsParameter,

  pushNotificationToZonedScheduleThereIsParameter,
  pushNotificationToShowThereIsParameter,
  cancelNotificationThereIsParameter
}