enum EnumBaseListModelDomainObjectOperationViewModel {
  getListModelFromLocalDatabaseThereIsParameterAndNoThereIsParameter,
  getListModelFromNetworkDatabaseThereIsParameterAndNoThereIsParameter,

  insertListModelToLocalDatabaseThereIsParameter,
  updateListModelToLocalDatabaseThereIsParameter,
  deleteListModelToLocalDatabaseThereIsParameter,

  insertListModelToNetworkDatabaseThereIsParameter,
  updateListModelToNetworkDatabaseThereIsParameter,
  deleteListModelToNetworkDatabaseThereIsParameter,
}