enum EnumBaseTypeParameterForGetModelLNDatabaseAndGetListLNDatabaseVM {
  getModelFromLocalDatabaseThereIsParameter,
  getModelFromNetworkDatabaseThereIsParameter,

  getListModelFromLocalDatabaseThereIsParameter,
  getListModelFromNetworkDatabaseThereIsParameter,
}