enum EnumBaseModelDomainVM {
  insertModelToLocalDatabaseForOneEntryThereIsParameter,
  getModelFromLocalDatabaseForOneEntry,

  insertModelToLocalDatabaseThereIsParameter,
  updateModelToLocalDatabaseThereIsParameter,
  deleteModelToLocalDatabaseThereIsParameter,
  getModelFromLocalDatabaseThereIsParameter,
  getListModelFromLocalDatabaseThereIsParameterAndNoThereIsParameter,

  insertModelToNetworkDatabaseThereIsParameter,
  updateModelToNetworkDatabaseThereIsParameter,
  deleteModelToNetworkDatabaseThereIsParameter,
  getModelFromNetworkDatabaseThereIsParameter,
  getListModelFromNetworkDatabaseThereIsParameterAndNoThereIsParameter,

  pushNotificationToZonedScheduleThereIsParameter,
  pushNotificationToShowThereIsParameter,
  cancelNotificationThereIsParameter
}