enum EnumBaseTypeParameterObjectOperationViewModel {
  getModelFromLocalDatabaseThereIsParameter,
  getModelFromNetworkDatabaseThereIsParameter,
  getListModelFromLocalDatabaseThereIsParameter,
  getListModelFromNetworkDatabaseThereIsParameter,
}