import 'package:library_arch_mvvm_modify_github_search/model/searchResultInLoading/ListSearchResultInLoading.dart';
import 'package:library_arch_mvvm_modify_github_search/model/searchResultInLoading/SearchResultInLoading.dart';
import 'package:library_architecture_mvvm_modify/base_model/interface_clone_stream_model_for_success/i_clone_stream_model_for_success.dart';
import 'package:library_architecture_mvvm_modify/utility/interface_stream_model/default_stream_model.dart';
import 'package:library_architecture_mvvm_modify/utility/interface_stream_model/i_stream_model.dart';

class CloneStreamSearchResultInLoadingForSuccess
    implements ICloneStreamModelForSuccess<SearchResultInLoading,ListSearchResultInLoading<SearchResultInLoading>>
{
  @override
  IStreamModel<SearchResultInLoading, ListSearchResultInLoading<SearchResultInLoading>>? cloneStreamModelForSuccess() {
    return DefaultStreamModel<SearchResultInLoading,ListSearchResultInLoading<SearchResultInLoading>>(SearchResultInLoading.getSearchResultInLoadingForSuccess,ListSearchResultInLoading.getListSearchResultInLoadingForSuccess);
  }

}