name: library_arch_mvvm_modify_firebase_login
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.0

dependencies:
  library_architecture_mvvm_modify:
    path: ../../packages/library_architecture_mvvm_modify
  flutter:
    sdk: flutter
  meta: ^1.8.0
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0
  formz: ^0.4.0
  google_fonts: ^3.0.1
  firebase_auth: ^4.0.2
  firebase_core: ^2.1.0
  google_sign_in: ^5.4.0
  # Unfortunately, a breaking change was introduced in 4.5.2.
  # https://github.com/firebase/flutterfire/issues/9806
  firebase_core_platform_interface: 4.5.1

dev_dependencies:
  test: ^1.21.4
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
