import 'package:library_architecture_mvvm_modify/base_data_source/interface_data_source/data_source.dart';
import 'package:library_architecture_mvvm_modify/base_model/base_list_model/base_list_model_domain.dart';
import 'package:library_architecture_mvvm_modify/base_model/base_list_model/base_list_model_named_database.dart';
import 'package:library_architecture_mvvm_modify/base_model/base_model_domain.dart';
import 'package:library_architecture_mvvm_modify/base_model/base_model_named_database.dart';
import 'package:library_architecture_mvvm_modify/base_view_model/base_view_model.dart';
import 'package:library_architecture_mvvm_modify/base_view_model/enum_base_list_model_domain_vm.dart';
import 'package:library_architecture_mvvm_modify/base_view_model/enum_base_model_domain_vm.dart';
import 'package:library_architecture_mvvm_modify/interface_check_inputs_data_by_user_and_calculate_before_function_view_model/delete_list_model_to_named_database_there_is_parameter_used_provider_base_list_model_domain_cidbuacbfvm.dart';
import 'package:library_architecture_mvvm_modify/interface_check_inputs_data_by_user_and_calculate_before_function_view_model/delete_model_to_named_database_there_is_parameter_used_provider_base_model_domain_cidbuacbfvm.dart';
import 'package:library_architecture_mvvm_modify/interface_check_inputs_data_by_user_and_calculate_before_function_view_model/insert_list_model_to_named_database_there_is_parameter_used_provider_base_list_model_domain_cidbuacbfvm.dart';
import 'package:library_architecture_mvvm_modify/interface_check_inputs_data_by_user_and_calculate_before_function_view_model/insert_model_to_named_database_there_is_parameter_used_provider_base_model_domain_cidbuacbfvm.dart';
import 'package:library_architecture_mvvm_modify/interface_check_inputs_data_by_user_and_calculate_before_function_view_model/update_list_model_to_named_database_there_is_parameter_used_provider_base_list_model_domain_cidbuacbfvm.dart';
import 'package:library_architecture_mvvm_modify/interface_check_inputs_data_by_user_and_calculate_before_function_view_model/update_model_to_named_database_there_is_parameter_used_provider_base_model_domain_cidbuacbfvm.dart';
import 'package:library_architecture_mvvm_modify/interface_converters_to_named_model/converter_to_base_list_model_named_database.dart';
import 'package:library_architecture_mvvm_modify/interface_converters_to_named_model/converter_to_base_model_named_database.dart';

class UserViewModel extends BaseViewModel {
  UserViewModel(DataSource<BaseModelNamedDatabase, BaseListModelNamedDatabase<BaseModelNamedDatabase>> dataSource, List<EnumBaseModelDomainVM> listEnumBaseModelDomainVM, List<EnumBaseListModelDomainVM> listEnumBaseListModelDomainVM, ItemCreator<BaseModelDomain> initCreatorBaseModelDomain, ItemCreator<BaseListModelDomain<BaseModelDomain>> initCreatorBaseListModelDomain, ConverterToBaseModelNamedDatabase<BaseModelDomain> converterToBaseModelNamedDatabase, ConverterToBaseListModelNamedDatabase<BaseListModelDomain<BaseModelDomain>> converterToBaseListModelNamedDatabase, InsertModelToNamedDatabaseThereIsParameterUsedProviderBaseModelDomainCIDBUACBFVM<BaseModelDomain> insertModelToLNDatabaseThereIsParameterUsedProviderBaseModelDomainCIDBUACBFVM, InsertListModelToNamedDatabaseThereIsParameterUsedProviderBaseListModelDomainCIDBUACBFVM<BaseListModelDomain<BaseModelDomain>> insertListModelToLNDatabaseThereIsParameterUsedProviderBaseListModelDomainCIDBUACBFVM, UpdateModelToNamedDatabaseThereIsParameterUsedProviderBaseModelDomainCIDBUACBFVM<BaseModelDomain> updateModelToLNDatabaseThereIsParameterUsedProviderBaseModelDomainCIDBUACBFVM, UpdateListModelToNamedDatabaseThereIsParameterUsedProviderBaseListModelDomainCIDBUACBFVM<BaseListModelDomain<BaseModelDomain>> updateListModelToLNDatabaseThereIsParameterUsedProviderBaseListModelDomainCIDBUACBFVM, DeleteModelToNamedDatabaseThereIsParameterUsedProviderBaseModelDomainCIDBUACBFVM<BaseModelDomain> deleteModelToLNDatabaseThereIsParameterUsedProviderBaseModelDomainCIDBUACBFVM, DeleteListModelToNamedDatabaseThereIsParameterUsedProviderBaseListModelDomainCIDBUACBFVM<BaseListModelDomain<BaseModelDomain>> deleteListModelToLNDatabaseThereIsParameterUsedProviderBaseListModelDomainCIDBUACBFVM) : super(dataSource, listEnumBaseModelDomainVM, listEnumBaseListModelDomainVM, initCreatorBaseModelDomain, initCreatorBaseListModelDomain, converterToBaseModelNamedDatabase, converterToBaseListModelNamedDatabase, insertModelToLNDatabaseThereIsParameterUsedProviderBaseModelDomainCIDBUACBFVM, insertListModelToLNDatabaseThereIsParameterUsedProviderBaseListModelDomainCIDBUACBFVM, updateModelToLNDatabaseThereIsParameterUsedProviderBaseModelDomainCIDBUACBFVM, updateListModelToLNDatabaseThereIsParameterUsedProviderBaseListModelDomainCIDBUACBFVM, deleteModelToLNDatabaseThereIsParameterUsedProviderBaseModelDomainCIDBUACBFVM, deleteListModelToLNDatabaseThereIsParameterUsedProviderBaseListModelDomainCIDBUACBFVM);


  /// Start Custom Methods Use Only To ListOfViewModelsUsingRealizedMethodsForMainView  **/



  /// End Custom Methods Use Only To ListOfViewModelsUsingRealizedMethodsForMainView  **/
}