import 'package:library_arch_mvvm_modify_counter/modelQNamedServiceViewModel/intQNoServiceViewModel/IntQNoServiceViewModelUsingGetNPForIncrementAndDecrement.dart';
import 'package:library_architecture_mvvm_modify/base_model/int.dart';

class IntQNoServiceUsingGetNPForIncrementAndDecrementListViewModelForIntTextWidget {
  final IntQNoServiceViewModelUsingGetNPForIncrementAndDecrement _intQNoServiceViewModelUsingGetNPForIncrementAndDecrement;

  IntQNoServiceUsingGetNPForIncrementAndDecrementListViewModelForIntTextWidget(this._intQNoServiceViewModelUsingGetNPForIncrementAndDecrement);

  Stream<Int>? get getStreamIntUsingGetNPForIncrementAndDecrement {
    return _intQNoServiceViewModelUsingGetNPForIncrementAndDecrement.getStreamIntUsingGetNPForIncrementAndDecrement;
  }
}