import 'package:library_architecture_mvvm_modify/base_exception/base_exception.dart';
import 'package:library_architecture_mvvm_modify/response.dart';

abstract class GetListModelFromLocalDatabaseDataSourceAndDeleteListModelToLocalDatabaseThereIsParameterDataSource {
  Future<Response<int,BaseException>> getListModelFromLocalDatabaseDataSourceAndDeleteListModelToLocalDatabaseThereIsParameterDataSource();
}