name: library_arch_mvvm_modify_counter
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.8

dependencies:
  library_architecture_mvvm_modify:
    path: ../../packages/library_architecture_mvvm_modify
  flutter:
    sdk: flutter
  meta: ^1.8.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  test: ^1.18.2
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
