name: library_architecture_mvvm_modify
description: MVVM Modify for Dart but you can also port to another language
version: 0.3.2
repository: https://github.com/antonpichka/library_architecture_mvvm_modify/tree/main/packages/library_architecture_mvvm_modify
issue_tracker: https://github.com/antonpichka/library_architecture_mvvm_modify/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.10.0
  ansicolor: ^2.0.2

dev_dependencies:
  lints: ^3.0.0