name: library_architecture_mvvm_modify
description: MVVM Modify for Dart and Flutter but you can also port to another language and to for specific library
version: 0.0.1
issue_tracker: https://github.com/JacobOdd/library_architecture_mvvm_modify/issues
homepage: https://github.com/JacobOdd/library_architecture_mvvm_modify
documentation: https://github.com/JacobOdd/library_architecture_mvvm_modify/blob/main/README.md#documentation

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  ansicolor: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

