name: library_architecture_mvvm_modify
description: MVVM Modify for Dart but you can also port to another language
version: 0.1.7
repository: https://github.com/antonpichka/library_architecture_mvvm_modify/tree/main/packages/library_architecture_mvvm_modify
issue_tracker: https://github.com/antonpichka/library_architecture_mvvm_modify/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.9.1
  ansicolor: ^2.0.1

dev_dependencies:
  lints: ^2.1.1