name: library_architecture_mvvm_modify
description: MVVM Modify for Dart but you can also port to another language
version: 0.0.2
repository: https://github.com/JacobOdd/library_architecture_mvvm_modify/tree/main/packages/library_architecture_mvvm_modify
homepage: https://github.com/JacobOdd/library_architecture_mvvm_modify/tree/main/packages/library_architecture_mvvm_modify
documentation: https://github.com/JacobOdd/library_architecture_mvvm_modify/tree/main/packages/library_architecture_mvvm_modify#documentation
issue_tracker: https://github.com/JacobOdd/library_architecture_mvvm_modify/issues

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  meta: ^1.8.0
  ansicolor: ^2.0.1

dev_dependencies:
  test: ^1.18.2
  flutter_lints: ^2.0.0

