import 'package:library_architecture_mvvm_modify/response_generic_bool_and_domain_exception.dart';

abstract class DeleteListModelToLNDatabaseCBFVM {
  ResponseGenericBoolAndDomainException deleteListModelToLNDatabaseCBFVM();
}