import 'package:library_architecture_mvvm_modify/base_model/base_model_domain.dart';
import 'package:library_architecture_mvvm_modify/interface_check_before_function_view_model/get_model_from_local_database_for_one_entry_cbfvm.dart';
import 'package:library_architecture_mvvm_modify/interface_check_before_function_view_model/provider_base_model_domain_cbfvm.dart';

abstract class GetModelFromLocalDatabaseForOneEntryUsedProviderBaseModelDomainCBFVM<T extends BaseModelDomain>
    implements GetModelFromLocalDatabaseForOneEntryCBFVM, ProviderBaseModelDomainCBFVM<T>
{
}