import 'package:flutter/cupertino.dart';
import 'package:library_architecture_mvvm_modify/base_exception/domain_exception.dart';
import 'package:library_architecture_mvvm_modify/base_exception/local_exception.dart';
import 'package:library_architecture_mvvm_modify/base_exception/network_exception.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/base_fvufvm_specifically_no_tip_yes_ns.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/delete_model_fvufvm/delete_model_to_list_model_domain_for_ln_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/delete_model_fvufvm/delete_model_to_list_model_domain_for_local_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/delete_model_fvufvm/delete_model_to_list_model_domain_for_network_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/delete_model_fvufvm/delete_model_to_ln_database_there_is_parameter_and_delete_model_to_list_model_domain_for_ln_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/delete_model_fvufvm/delete_model_to_ln_database_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/delete_model_fvufvm/delete_model_to_local_database_there_is_parameter_and_delete_model_to_list_model_domain_for_local_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/delete_model_fvufvm/delete_model_to_local_database_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/delete_model_fvufvm/delete_model_to_network_database_there_is_parameter_and_delete_model_to_list_model_domain_for_network_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/delete_model_fvufvm/delete_model_to_network_database_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/get_list_model_from_database_there_is_parameter_fvufvm/get_list_model_from_ln_database_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/get_list_model_from_database_there_is_parameter_fvufvm/get_list_model_from_local_database_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/get_list_model_from_database_there_is_parameter_fvufvm/get_list_model_from_network_database_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/get_model_from_database_there_is_parameter_fvufvm/get_model_from_ln_database_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/get_model_from_database_there_is_parameter_fvufvm/get_model_from_local_database_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/get_model_from_database_there_is_parameter_fvufvm/get_model_from_network_database_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/insert_model_fvufvm/insert_model_to_list_model_domain_for_ln_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/insert_model_fvufvm/insert_model_to_list_model_domain_for_local_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/insert_model_fvufvm/insert_model_to_list_model_domain_for_network_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/insert_model_fvufvm/insert_model_to_ln_database_there_is_parameter_and_insert_model_to_list_model_domain_for_ln_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/insert_model_fvufvm/insert_model_to_ln_database_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/insert_model_fvufvm/insert_model_to_local_database_there_is_parameter_and_insert_model_to_list_model_domain_for_local_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/insert_model_fvufvm/insert_model_to_local_database_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/insert_model_fvufvm/insert_model_to_network_database_there_is_parameter_and_insert_model_to_list_model_domain_for_network_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/insert_model_fvufvm/insert_model_to_network_database_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/iterator_for_list_model_database_fvufvm/iterator_for_list_model_ln_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/iterator_for_list_model_database_fvufvm/iterator_for_list_model_local_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/iterator_for_list_model_database_fvufvm/iterator_for_list_model_network_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/model_domain_notification_fvufvm/cancel_notification_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/model_domain_notification_fvufvm/push_notification_to_show_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/model_domain_notification_fvufvm/push_notification_to_zoned_schedule_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/model_local_database_for_one_entry_fvufvm/insert_model_to_local_database_for_one_entry_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/update_model_fvufvm/update_model_to_list_model_domain_for_ln_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/update_model_fvufvm/update_model_to_list_model_domain_for_local_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/update_model_fvufvm/update_model_to_list_model_domain_for_network_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/update_model_fvufvm/update_model_to_ln_database_there_is_parameter_and_update_model_to_list_model_domain_for_ln_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/update_model_fvufvm/update_model_to_ln_database_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/update_model_fvufvm/update_model_to_local_database_there_is_parameter_and_update_model_to_list_model_domain_for_local_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/update_model_fvufvm/update_model_to_local_database_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/update_model_fvufvm/update_model_to_network_database_there_is_parameter_and_update_model_to_list_model_domain_for_network_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/update_model_fvufvm/update_model_to_network_database_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_model/base_model_domain.dart';
import 'package:library_architecture_mvvm_modify/base_view_model/base_view_model.dart';
import 'package:library_architecture_mvvm_modify/base_view_model/enum_base_model_domain_object_operation_view_model.dart';

abstract class BaseFVUFVMSpecificallyYesTIPYesNS<T,Y>
    extends BaseFVUFVMSpecificallyNoTIPYesNS<T>
{
  static final GetListModelFromLNDatabaseThereIsParameterFVUFVM _getListModelFromLNDatabaseThereIsParameterFVUFVM = GetListModelFromLNDatabaseThereIsParameterFVUFVM();
  static final GetListModelFromLocalDatabaseThereIsParameterFVUFVM _getListModelFromLocalDatabaseThereIsParameterFVUFVM = GetListModelFromLocalDatabaseThereIsParameterFVUFVM();
  static final GetListModelFromNetworkDatabaseThereIsParameterFVUFVM _getListModelFromNetworkDatabaseThereIsParameterFVUFVM = GetListModelFromNetworkDatabaseThereIsParameterFVUFVM();

  static final GetModelFromLNDatabaseThereIsParameterFVUFVM _getModelFromLNDatabaseThereIsParameterFVUFVM = GetModelFromLNDatabaseThereIsParameterFVUFVM();
  static final GetModelFromLocalDatabaseThereIsParameterFVUFVM _getModelFromLocalDatabaseThereIsParameterFVUFVM = GetModelFromLocalDatabaseThereIsParameterFVUFVM();
  static final GetModelFromNetworkDatabaseThereIsParameterFVUFVM _getModelFromNetworkDatabaseThereIsParameterFVUFVM = GetModelFromNetworkDatabaseThereIsParameterFVUFVM();

  static final InsertModelToListModelDomainForLNDatabaseFVUFVM _insertModelToListModelDomainForLNDatabaseFVUFVM = InsertModelToListModelDomainForLNDatabaseFVUFVM();
  static final InsertModelToListModelDomainForLocalDatabaseFVUFVM _insertModelToListModelDomainForLocalDatabaseFVUFVM = InsertModelToListModelDomainForLocalDatabaseFVUFVM();
  static final InsertModelToListModelDomainForNetworkDatabaseFVUFVM _insertModelToListModelDomainForNetworkDatabaseFVUFVM = InsertModelToListModelDomainForNetworkDatabaseFVUFVM();
  static final InsertModelToLNDatabaseThereIsParameterAndInsertModelToListModelDomainForLNDatabaseFVUFVM _insertModelToLNDatabaseThereIsParameterAndInsertModelToListModelDomainForLNDatabaseFVUFVM = InsertModelToLNDatabaseThereIsParameterAndInsertModelToListModelDomainForLNDatabaseFVUFVM();
  static final InsertModelToLNDatabaseThereIsParameterFVUFVM _insertModelToLNDatabaseThereIsParameterFVUFVM = InsertModelToLNDatabaseThereIsParameterFVUFVM();
  static final InsertModelToLocalDatabaseThereIsParameterAndInsertModelToListModelDomainForLocalDatabaseFVUFVM _insertModelToLocalDatabaseThereIsParameterAndInsertModelToListModelDomainForLocalDatabaseFVUFVM = InsertModelToLocalDatabaseThereIsParameterAndInsertModelToListModelDomainForLocalDatabaseFVUFVM();
  static final InsertModelToLocalDatabaseThereIsParameterFVUFVM _insertModelToLocalDatabaseThereIsParameterFVUFVM = InsertModelToLocalDatabaseThereIsParameterFVUFVM();
  static final InsertModelToNetworkDatabaseThereIsParameterAndInsertModelToListModelDomainForNetworkDatabaseFVUFVM _insertModelToNetworkDatabaseThereIsParameterAndInsertModelToListModelDomainForNetworkDatabaseFVUFVM = InsertModelToNetworkDatabaseThereIsParameterAndInsertModelToListModelDomainForNetworkDatabaseFVUFVM();
  static final InsertModelToNetworkDatabaseThereIsParameterFVUFVM _insertModelToNetworkDatabaseThereIsParameterFVUFVM = InsertModelToNetworkDatabaseThereIsParameterFVUFVM();

  static final UpdateModelToListModelDomainForLNDatabaseFVUFVM _updateModelToListModelDomainForLNDatabaseFVUFVM = UpdateModelToListModelDomainForLNDatabaseFVUFVM();
  static final UpdateModelToListModelDomainForLocalDatabaseFVUFVM _updateModelToListModelDomainForLocalDatabaseFVUFVM = UpdateModelToListModelDomainForLocalDatabaseFVUFVM();
  static final UpdateModelToListModelDomainForNetworkDatabaseFVUFVM _updateModelToListModelDomainForNetworkDatabaseFVUFVM = UpdateModelToListModelDomainForNetworkDatabaseFVUFVM();
  static final UpdateModelToLNDatabaseThereIsParameterAndUpdateModelToListModelDomainForLNDatabaseFVUFVM _updateModelToLNDatabaseThereIsParameterAndUpdateModelToListModelDomainForLNDatabaseFVUFVM = UpdateModelToLNDatabaseThereIsParameterAndUpdateModelToListModelDomainForLNDatabaseFVUFVM();
  static final UpdateModelToLNDatabaseThereIsParameterFVUFVM _updateModelToLNDatabaseThereIsParameterFVUFVM = UpdateModelToLNDatabaseThereIsParameterFVUFVM();
  static final UpdateModelToLocalDatabaseThereIsParameterAndUpdateModelToListModelDomainForLocalDatabaseFVUFVM _updateModelToLocalDatabaseThereIsParameterAndUpdateModelToListModelDomainForLocalDatabaseFVUFVM = UpdateModelToLocalDatabaseThereIsParameterAndUpdateModelToListModelDomainForLocalDatabaseFVUFVM();
  static final UpdateModelToLocalDatabaseThereIsParameterFVUFVM _updateModelToLocalDatabaseThereIsParameterFVUFVM = UpdateModelToLocalDatabaseThereIsParameterFVUFVM();
  static final UpdateModelToNetworkDatabaseThereIsParameterAndUpdateModelToListModelDomainForNetworkDatabaseFVUFVM _updateModelToNetworkDatabaseThereIsParameterAndUpdateModelToListModelDomainForNetworkDatabaseFVUFVM = UpdateModelToNetworkDatabaseThereIsParameterAndUpdateModelToListModelDomainForNetworkDatabaseFVUFVM();
  static final UpdateModelToNetworkDatabaseThereIsParameterFVUFVM _updateModelToNetworkDatabaseThereIsParameterFVUFVM = UpdateModelToNetworkDatabaseThereIsParameterFVUFVM();

  static final DeleteModelToListModelDomainForLNDatabaseFVUFVM _deleteModelToListModelDomainForLNDatabaseFVUFVM = DeleteModelToListModelDomainForLNDatabaseFVUFVM();
  static final DeleteModelToListModelDomainForLocalDatabaseFVUFVM _deleteModelToListModelDomainForLocalDatabaseFVUFVM = DeleteModelToListModelDomainForLocalDatabaseFVUFVM();
  static final DeleteModelToListModelDomainForNetworkDatabaseFVUFVM _deleteModelToListModelDomainForNetworkDatabaseFVUFVM = DeleteModelToListModelDomainForNetworkDatabaseFVUFVM();
  static final DeleteModelToLNDatabaseThereIsParameterAndDeleteModelToListModelDomainForLNDatabaseFVUFVM _deleteModelToLNDatabaseThereIsParameterAndDeleteModelToListModelDomainForLNDatabaseFVUFVM = DeleteModelToLNDatabaseThereIsParameterAndDeleteModelToListModelDomainForLNDatabaseFVUFVM();
  static final DeleteModelToLNDatabaseThereIsParameterFVUFVM _deleteModelToLNDatabaseThereIsParameterFVUFVM = DeleteModelToLNDatabaseThereIsParameterFVUFVM();
  static final DeleteModelToLocalDatabaseThereIsParameterAndDeleteModelToListModelDomainForLocalDatabaseFVUFVM _deleteModelToLocalDatabaseThereIsParameterAndDeleteModelToListModelDomainForLocalDatabaseFVUFVM = DeleteModelToLocalDatabaseThereIsParameterAndDeleteModelToListModelDomainForLocalDatabaseFVUFVM();
  static final DeleteModelToLocalDatabaseThereIsParameterFVUFVM _deleteModelToLocalDatabaseThereIsParameterFVUFVM = DeleteModelToLocalDatabaseThereIsParameterFVUFVM();
  static final DeleteModelToNetworkDatabaseThereIsParameterAndDeleteModelToListModelDomainForNetworkDatabaseFVUFVM _deleteModelToNetworkDatabaseThereIsParameterAndDeleteModelToListModelDomainForNetworkDatabaseFVUFVM = DeleteModelToNetworkDatabaseThereIsParameterAndDeleteModelToListModelDomainForNetworkDatabaseFVUFVM();
  static final DeleteModelToNetworkDatabaseThereIsParameterFVUFVM _deleteModelToNetworkDatabaseThereIsParameterFVUFVM = DeleteModelToNetworkDatabaseThereIsParameterFVUFVM();

  static final IteratorForListModelLNDatabaseFVUFVM _iteratorForListModelLNDatabaseFVUFVM = IteratorForListModelLNDatabaseFVUFVM();
  static final IteratorForListModelLocalDatabaseFVUFVM _iteratorForListModelLocalDatabaseFVUFVM = IteratorForListModelLocalDatabaseFVUFVM();
  static final IteratorForListModelNetworkDatabaseFVUFVM _iteratorForListModelNetworkDatabaseFVUFVM = IteratorForListModelNetworkDatabaseFVUFVM();

  static final InsertModelToLocalDatabaseForOneEntryThereIsParameterFVUFVM _insertModelLocalDatabaseForOneEntryThereIsParameterFVUFVM = InsertModelToLocalDatabaseForOneEntryThereIsParameterFVUFVM();

  static final CancelNotificationThereIsParameterFVUFVM _cancelNotificationThereIsParameterFVUFVM = CancelNotificationThereIsParameterFVUFVM();
  static final PushNotificationToShowThereIsParameterFVUFVM _pushNotificationToShowThereIsParameterFVUFVM = PushNotificationToShowThereIsParameterFVUFVM();
  static final PushNotificationToZonedScheduleThereIsParameterFVUFVM _pushNotificationToZonedScheduleThereIsParameterFVUFVM = PushNotificationToZonedScheduleThereIsParameterFVUFVM();

  /* Start Method CallToMethodGetListModelFromLNDatabaseThereIsParameterAndUseTheSettersFVUFVM */

  static GetListModelFromLNDatabaseThereIsParameterFVUFVM get getListModelFromLNDatabaseThereIsParameterFVUFVM {
    return _getListModelFromLNDatabaseThereIsParameterFVUFVM;
  }

  static GetListModelFromLocalDatabaseThereIsParameterFVUFVM get getListModelFromLocalDatabaseThereIsParameterFVUFVM {
    return _getListModelFromLocalDatabaseThereIsParameterFVUFVM;
  }

  static GetListModelFromNetworkDatabaseThereIsParameterFVUFVM get getListModelFromNetworkDatabaseThereIsParameterFVUFVM {
    return _getListModelFromNetworkDatabaseThereIsParameterFVUFVM;
  }

  /* End Method CallToMethodGetListModelFromLNDatabaseThereIsParameterAndUseTheSettersFVUFVM */

  /* Start Method CallToMethodGetModelFromLNDatabaseThereIsParameterAndUseTheSettersFVUFVM */

  static GetModelFromLNDatabaseThereIsParameterFVUFVM get getModelFromLNDatabaseThereIsParameterFVUFVM {
    return _getModelFromLNDatabaseThereIsParameterFVUFVM;
  }

  static GetModelFromLocalDatabaseThereIsParameterFVUFVM get getModelFromLocalDatabaseThereIsParameterFVUFVM {
    return _getModelFromLocalDatabaseThereIsParameterFVUFVM;
  }

  static GetModelFromNetworkDatabaseThereIsParameterFVUFVM get getModelFromNetworkDatabaseThereIsParameterFVUFVM {
    return _getModelFromNetworkDatabaseThereIsParameterFVUFVM;
  }

  /* End Method CallToMethodGetModelFromLNDatabaseThereIsParameterAndUseTheSettersFVUFVM */

  /* Start Method InsertModelFVUFVM */

  static InsertModelToListModelDomainForLNDatabaseFVUFVM get getInsertModelToListModelDomainForLNDatabaseFVUFVM {
    return _insertModelToListModelDomainForLNDatabaseFVUFVM;
  }

  static InsertModelToListModelDomainForLocalDatabaseFVUFVM get getInsertModelToListModelDomainForLocalDatabaseFVUFVM {
    return _insertModelToListModelDomainForLocalDatabaseFVUFVM;
  }

  static InsertModelToListModelDomainForNetworkDatabaseFVUFVM get getInsertModelToListModelDomainForNetworkDatabaseFVUFVM {
    return _insertModelToListModelDomainForNetworkDatabaseFVUFVM;
  }

  static InsertModelToLNDatabaseThereIsParameterAndInsertModelToListModelDomainForLNDatabaseFVUFVM get getInsertModelToLNDatabaseThereIsParameterAndInsertModelToListModelDomainForLNDatabaseFVUFVM {
    return _insertModelToLNDatabaseThereIsParameterAndInsertModelToListModelDomainForLNDatabaseFVUFVM;
  }

  static InsertModelToLNDatabaseThereIsParameterFVUFVM get getInsertModelToLNDatabaseThereIsParameterFVUFVM {
    return _insertModelToLNDatabaseThereIsParameterFVUFVM;
  }

  static InsertModelToLocalDatabaseThereIsParameterAndInsertModelToListModelDomainForLocalDatabaseFVUFVM get getInsertModelToLocalDatabaseThereIsParameterAndInsertModelToListModelDomainForLocalDatabaseFVUFVM {
    return _insertModelToLocalDatabaseThereIsParameterAndInsertModelToListModelDomainForLocalDatabaseFVUFVM;
  }

  static InsertModelToLocalDatabaseThereIsParameterFVUFVM get getInsertModelToLocalDatabaseThereIsParameterFVUFVM {
    return _insertModelToLocalDatabaseThereIsParameterFVUFVM;
  }

  static InsertModelToNetworkDatabaseThereIsParameterAndInsertModelToListModelDomainForNetworkDatabaseFVUFVM get getInsertModelToNetworkDatabaseThereIsParameterAndInsertModelToListModelDomainForNetworkDatabaseFVUFVM {
    return _insertModelToNetworkDatabaseThereIsParameterAndInsertModelToListModelDomainForNetworkDatabaseFVUFVM;
  }

  static InsertModelToNetworkDatabaseThereIsParameterFVUFVM get getInsertModelToNetworkDatabaseThereIsParameterFVUFVM {
    return _insertModelToNetworkDatabaseThereIsParameterFVUFVM;
  }

  /* End Method InsertModelFVUFVM */

  /* Start Method UpdateModelFVUFVM */

  static UpdateModelToListModelDomainForLNDatabaseFVUFVM get getUpdateModelToListModelDomainForLNDatabaseFVUFVM {
    return _updateModelToListModelDomainForLNDatabaseFVUFVM;
  }

  static UpdateModelToListModelDomainForLocalDatabaseFVUFVM get getUpdateModelToListModelDomainForLocalDatabaseFVUFVM {
    return _updateModelToListModelDomainForLocalDatabaseFVUFVM;
  }

  static UpdateModelToListModelDomainForNetworkDatabaseFVUFVM get getUpdateModelToListModelDomainForNetworkDatabaseFVUFVM {
    return _updateModelToListModelDomainForNetworkDatabaseFVUFVM;
  }

  static UpdateModelToLNDatabaseThereIsParameterAndUpdateModelToListModelDomainForLNDatabaseFVUFVM get getUpdateModelToLNDatabaseThereIsParameterAndUpdateModelToListModelDomainForLNDatabaseFVUFVM {
    return _updateModelToLNDatabaseThereIsParameterAndUpdateModelToListModelDomainForLNDatabaseFVUFVM;
  }

  static UpdateModelToLNDatabaseThereIsParameterFVUFVM get getUpdateModelToLNDatabaseThereIsParameterFVUFVM {
    return _updateModelToLNDatabaseThereIsParameterFVUFVM;
  }

  static UpdateModelToLocalDatabaseThereIsParameterAndUpdateModelToListModelDomainForLocalDatabaseFVUFVM get getUpdateModelToLocalDatabaseThereIsParameterAndUpdateModelToListModelDomainForLocalDatabaseFVUFVM {
    return _updateModelToLocalDatabaseThereIsParameterAndUpdateModelToListModelDomainForLocalDatabaseFVUFVM;
  }

  static UpdateModelToLocalDatabaseThereIsParameterFVUFVM get getUpdateModelToLocalDatabaseThereIsParameterFVUFVM {
    return _updateModelToLocalDatabaseThereIsParameterFVUFVM;
  }

  static UpdateModelToNetworkDatabaseThereIsParameterAndUpdateModelToListModelDomainForNetworkDatabaseFVUFVM get getUpdateModelToNetworkDatabaseThereIsParameterAndUpdateModelToListModelDomainForNetworkDatabaseFVUFVM {
    return _updateModelToNetworkDatabaseThereIsParameterAndUpdateModelToListModelDomainForNetworkDatabaseFVUFVM;
  }

  static UpdateModelToNetworkDatabaseThereIsParameterFVUFVM get getUpdateModelToNetworkDatabaseThereIsParameterFVUFVM {
    return _updateModelToNetworkDatabaseThereIsParameterFVUFVM;
  }

  /* End Method UpdateModelFVUFVM */

  /* Start Method DeleteModelFVUFVM */

  static DeleteModelToListModelDomainForLNDatabaseFVUFVM get getDeleteModelToListModelDomainForLNDatabaseFVUFVM {
    return _deleteModelToListModelDomainForLNDatabaseFVUFVM;
  }

  static DeleteModelToListModelDomainForLocalDatabaseFVUFVM get getDeleteModelToListModelDomainForLocalDatabaseFVUFVM {
    return _deleteModelToListModelDomainForLocalDatabaseFVUFVM;
  }

  static DeleteModelToListModelDomainForNetworkDatabaseFVUFVM get getDeleteModelToListModelDomainForNetworkDatabaseFVUFVM {
    return _deleteModelToListModelDomainForNetworkDatabaseFVUFVM;
  }

  static DeleteModelToLNDatabaseThereIsParameterAndDeleteModelToListModelDomainForLNDatabaseFVUFVM get getDeleteModelToLNDatabaseThereIsParameterAndDeleteModelToListModelDomainForLNDatabaseFVUFVM {
    return _deleteModelToLNDatabaseThereIsParameterAndDeleteModelToListModelDomainForLNDatabaseFVUFVM;
  }

  static DeleteModelToLNDatabaseThereIsParameterFVUFVM get getDeleteModelToLNDatabaseThereIsParameterFVUFVM {
    return _deleteModelToLNDatabaseThereIsParameterFVUFVM;
  }

  static DeleteModelToLocalDatabaseThereIsParameterAndDeleteModelToListModelDomainForLocalDatabaseFVUFVM get getDeleteModelToLocalDatabaseThereIsParameterAndDeleteModelToListModelDomainForLocalDatabaseFVUFVM {
    return _deleteModelToLocalDatabaseThereIsParameterAndDeleteModelToListModelDomainForLocalDatabaseFVUFVM;
  }

  static DeleteModelToLocalDatabaseThereIsParameterFVUFVM get getDeleteModelToLocalDatabaseThereIsParameterFVUFVM {
    return _deleteModelToLocalDatabaseThereIsParameterFVUFVM;
  }

  static DeleteModelToNetworkDatabaseThereIsParameterAndDeleteModelToListModelDomainForNetworkDatabaseFVUFVM get getDeleteModelToNetworkDatabaseThereIsParameterAndDeleteModelToListModelDomainForNetworkDatabaseFVUFVM {
    return _deleteModelToNetworkDatabaseThereIsParameterAndDeleteModelToListModelDomainForNetworkDatabaseFVUFVM;
  }

  static DeleteModelToNetworkDatabaseThereIsParameterFVUFVM get getDeleteModelToNetworkDatabaseThereIsParameterFVUFVM {
    return _deleteModelToNetworkDatabaseThereIsParameterFVUFVM;
  }

  /* End Method DeleteModelFVUFVM */

  /* Start Method IteratorForListModelLNDatabaseFVUFVM */

  static IteratorForListModelLNDatabaseFVUFVM get getIteratorForListModelLNDatabaseFVUFVM {
    return _iteratorForListModelLNDatabaseFVUFVM;
  }

  static IteratorForListModelLocalDatabaseFVUFVM get getIteratorForListModelLocalDatabaseFVUFVM {
    return _iteratorForListModelLocalDatabaseFVUFVM;
  }

  static IteratorForListModelNetworkDatabaseFVUFVM get getIteratorForListModelNetworkDatabaseFVUFVM {
    return _iteratorForListModelNetworkDatabaseFVUFVM;
  }

  /* End Method IteratorForListModelLNDatabaseFVUFVM */

  /* Start Method InsertModelLocalDatabaseForOneEntryThereIsParameterFVUFVM */

  static InsertModelToLocalDatabaseForOneEntryThereIsParameterFVUFVM get getInsertModelLocalDatabaseForOneEntryThereIsParameterFVUFVM {
    return _insertModelLocalDatabaseForOneEntryThereIsParameterFVUFVM;
  }

  /* End Method InsertModelLocalDatabaseForOneEntryThereIsParameterFVUFVM */

  /* Start Method ModelDomainNotificationFVUFVM */

  static CancelNotificationThereIsParameterFVUFVM get getCancelNotificationThereIsParameterFVUFVM {
    return _cancelNotificationThereIsParameterFVUFVM;
  }

  static PushNotificationToShowThereIsParameterFVUFVM get getPushNotificationToShowThereIsParameterFVUFVM {
    return _pushNotificationToShowThereIsParameterFVUFVM;
  }

  static PushNotificationToZonedScheduleThereIsParameterFVUFVM get getPushNotificationToZonedScheduleThereIsParameterFVUFVM {
    return _pushNotificationToZonedScheduleThereIsParameterFVUFVM;
  }

  /* End Method ModelDomainNotificationFVUFVM */

  void setObject(BaseViewModel baseViewModel, Y object);

  Future<void> setObjectAndMainMethod(
      T paramMainMethod,
      BaseViewModel baseViewModel,
      Y object,
      Function functionForResultSuccess,
      Function(DomainException) functionForResultDomainException,
      Function(LocalException) functionForResultLocalException,
      Function(NetworkException) functionForResultNetworkException)
  async {
    setObject(baseViewModel, object);
    mainMethod(
        paramMainMethod,
        functionForResultSuccess,
        functionForResultDomainException,
        functionForResultLocalException,
        functionForResultNetworkException
    );
  }

  Future<void> setObjectAndMainMethodAndNotifyStream(
      T paramMainMethod,
      BaseViewModel baseViewModel,
      Y object,
      Function functionForResultSuccess,
      Function(DomainException) functionForResultDomainException,
      Function(LocalException) functionForResultLocalException,
      Function(NetworkException) functionForResultNetworkException)
  async {
    setObject(baseViewModel, object);
    mainMethod(
        paramMainMethod,
        functionForResultSuccess,
        functionForResultDomainException,
        functionForResultLocalException,
        functionForResultNetworkException
    );
    notifyStream(baseViewModel);
  }
  
  @protected
  void beforeCodeIsCheckTypeBaseModelDomainAndAlsoUsedFunctionSetModelDomain(
      BaseViewModel baseViewModel,
      BaseModelDomain baseModelDomain,
      EnumBaseModelDomainObjectOperationViewModel operation,
     )
  {
    if(baseViewModel.getTypeBaseModelDomain != baseModelDomain.runtimeType) {
      throw Exception("viewModel type baseModelDomain | not equals | type baseModelDomain. ViewModelType: ${baseViewModel.runtimeType}");
    }

    baseViewModel.setModelDomain(
        baseModelDomain,
        operation
    );
  }
}
