import 'package:flutter/cupertino.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/get_list_model_from_database_fvufvm/get_list_model_from_ln_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/get_list_model_from_database_fvufvm/get_list_model_from_local_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/get_list_model_from_database_fvufvm/get_list_model_from_network_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/get_list_model_from_database_there_is_parameter_fvufvm/get_list_model_from_ln_database_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/get_list_model_from_database_there_is_parameter_fvufvm/get_list_model_from_local_database_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/get_list_model_from_database_there_is_parameter_fvufvm/get_list_model_from_network_database_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/get_model_from_database_there_is_parameter_fvufvm/get_model_from_ln_database_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/get_model_from_database_there_is_parameter_fvufvm/get_model_from_local_database_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/get_model_from_database_there_is_parameter_fvufvm/get_model_from_network_database_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/insert_model_fvufvm/insert_model_to_list_model_domain_for_ln_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/insert_model_fvufvm/insert_model_to_list_model_domain_for_local_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/insert_model_fvufvm/insert_model_to_list_model_domain_for_network_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/insert_model_fvufvm/insert_model_to_ln_database_there_is_parameter_and_insert_model_to_list_model_domain_for_ln_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/insert_model_fvufvm/insert_model_to_ln_database_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/insert_model_fvufvm/insert_model_to_local_database_there_is_parameter_and_insert_model_to_list_model_domain_for_local_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/insert_model_fvufvm/insert_model_to_local_database_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/insert_model_fvufvm/insert_model_to_network_database_there_is_parameter_and_insert_model_to_list_model_domain_for_network_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/insert_model_fvufvm/insert_model_to_network_database_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_model/base_model_domain.dart';
import 'package:library_architecture_mvvm_modify/base_view_model/base_view_model.dart';

 /* 4 methods for 1 methods owned by classes FunctionViewModel

 /*  Start Variant: No There Is Parameter */

 /*
   1) void FUNCTION_VIEW_MODEL
   2) void FUNCTION_VIEW_MODEL and NotifyStream.. ModelDomain/ListModelDomain
   3) NotifyStream.. ModelDomain/ListModelDomain

 */

 /*  End Variant: No There Is Parameter */

 /* Start Variant: There Is Parameter */

 /*
   1) void FUNCTION_VIEW_MODEL
   2) void FUNCTION_VIEW_MODEL and NotifyStream.. ModelDomain/ListModelDomain
   3) void set.. BaseParameter/ModelDomain and FUNCTION_VIEW_MODEL
   4) void set.. BaseParameter/ModelDomain and FUNCTION_VIEW_MODEL and NotifyStream.. ModelDomain/ListModelDomain
   5) void set.. BaseParameter/ModelDomain
   6) NotifyStream.. ModelDomain/ListModelDomain

 */

  /* End Variant: There Is Parameter */

  */

class BaseFunctionViewUsingFunctionViewModel {

  static final GetListModelFromLNDatabaseFVUFVM _getListModelFromLNDatabaseFVUFVM = GetListModelFromLNDatabaseFVUFVM();
  static final GetListModelFromLocalDatabaseFVUFVM _getListModelFromLocalDatabaseFVUFVM = GetListModelFromLocalDatabaseFVUFVM();
  static final GetListModelFromNetworkDatabaseFVUFVM _getListModelFromNetworkDatabaseFVUFVM = GetListModelFromNetworkDatabaseFVUFVM();

  static final GetListModelFromLNDatabaseThereIsParameterFVUFVM _getListModelFromLNDatabaseThereIsParameterFVUFVM = GetListModelFromLNDatabaseThereIsParameterFVUFVM();
  static final GetListModelFromLocalDatabaseThereIsParameterFVUFVM _getListModelFromLocalDatabaseThereIsParameterFVUFVM = GetListModelFromLocalDatabaseThereIsParameterFVUFVM();
  static final GetListModelFromNetworkDatabaseThereIsParameterFVUFVM _getListModelFromNetworkDatabaseThereIsParameterFVUFVM = GetListModelFromNetworkDatabaseThereIsParameterFVUFVM();

  static final GetModelFromLNDatabaseThereIsParameterFVUFVM _getModelFromLNDatabaseThereIsParameterFVUFVM = GetModelFromLNDatabaseThereIsParameterFVUFVM();
  static final GetModelFromLocalDatabaseThereIsParameterFVUFVM _getModelFromLocalDatabaseThereIsParameterFVUFVM = GetModelFromLocalDatabaseThereIsParameterFVUFVM();
  static final GetModelFromNetworkDatabaseThereIsParameterFVUFVM _getModelFromNetworkDatabaseThereIsParameterFVUFVM = GetModelFromNetworkDatabaseThereIsParameterFVUFVM();

  static final InsertModelToListModelDomainForLNDatabaseFVUFVM _insertModelToListModelDomainForLNDatabaseFVUFVM = InsertModelToListModelDomainForLNDatabaseFVUFVM();
  static final InsertModelToListModelDomainForLocalDatabaseFVUFVM _insertModelToListModelDomainForLocalDatabaseFVUFVM = InsertModelToListModelDomainForLocalDatabaseFVUFVM();
  static final InsertModelToListModelDomainForNetworkDatabaseFVUFVM _insertModelToListModelDomainForNetworkDatabaseFVUFVM = InsertModelToListModelDomainForNetworkDatabaseFVUFVM();
  static final InsertModelToLNDatabaseThereIsParameterAndInsertModelToListModelDomainForLNDatabaseFVUFVM _insertModelToLNDatabaseThereIsParameterAndInsertModelToListModelDomainForLNDatabaseFVUFVM = InsertModelToLNDatabaseThereIsParameterAndInsertModelToListModelDomainForLNDatabaseFVUFVM();
  static final InsertModelToLNDatabaseThereIsParameterFVUFVM _insertModelToLNDatabaseThereIsParameterFVUFVM = InsertModelToLNDatabaseThereIsParameterFVUFVM();
  static final InsertModelToLocalDatabaseThereIsParameterAndInsertModelToListModelDomainForLocalDatabaseFVUFVM _insertModelToLocalDatabaseThereIsParameterAndInsertModelToListModelDomainForLocalDatabaseFVUFVM = InsertModelToLocalDatabaseThereIsParameterAndInsertModelToListModelDomainForLocalDatabaseFVUFVM();
  static final InsertModelToLocalDatabaseThereIsParameterFVUFVM _insertModelToLocalDatabaseThereIsParameterFVUFVM = InsertModelToLocalDatabaseThereIsParameterFVUFVM();
  static final InsertModelToNetworkDatabaseThereIsParameterAndInsertModelToListModelDomainForNetworkDatabaseFVUFVM _insertModelToNetworkDatabaseThereIsParameterAndInsertModelToListModelDomainForNetworkDatabaseFVUFVM = InsertModelToNetworkDatabaseThereIsParameterAndInsertModelToListModelDomainForNetworkDatabaseFVUFVM();
  static final InsertModelToNetworkDatabaseThereIsParameterFVUFVM _insertModelToNetworkDatabaseThereIsParameterFVUFVM = InsertModelToNetworkDatabaseThereIsParameterFVUFVM();

  /* Start Method CallToMethodGetListModelFromLNDatabaseAndUseTheSettersFVUFVM */

  static GetListModelFromLNDatabaseFVUFVM get getListModelFromLNDatabaseFVUFVM {
    return _getListModelFromLNDatabaseFVUFVM;
  }

  static GetListModelFromLocalDatabaseFVUFVM get getListModelFromLocalDatabaseFVUFVM {
    return _getListModelFromLocalDatabaseFVUFVM;
  }

  static GetListModelFromNetworkDatabaseFVUFVM get getListModelFromNetworkDatabaseFVUFVM {
    return _getListModelFromNetworkDatabaseFVUFVM;
  }

  /* End Method CallToMethodGetListModelFromLNDatabaseAndUseTheSettersFVUFVM */

  /* Start Method CallToMethodGetListModelFromLNDatabaseThereIsParameterAndUseTheSettersFVUFVM */

  static GetListModelFromLNDatabaseThereIsParameterFVUFVM get getListModelFromLNDatabaseThereIsParameterFVUFVM {
    return _getListModelFromLNDatabaseThereIsParameterFVUFVM;
  }

  static GetListModelFromLocalDatabaseThereIsParameterFVUFVM get getListModelFromLocalDatabaseThereIsParameterFVUFVM {
    return _getListModelFromLocalDatabaseThereIsParameterFVUFVM;
  }

  static GetListModelFromNetworkDatabaseThereIsParameterFVUFVM get getListModelFromNetworkDatabaseThereIsParameterFVUFVM {
    return _getListModelFromNetworkDatabaseThereIsParameterFVUFVM;
  }

  /* End Method CallToMethodGetListModelFromLNDatabaseThereIsParameterAndUseTheSettersFVUFVM */

  /* Start Method CallToMethodGetModelFromLNDatabaseThereIsParameterAndUseTheSettersFVUFVM */

  static GetModelFromLNDatabaseThereIsParameterFVUFVM get getModelFromLNDatabaseThereIsParameterFVUFVM {
    return _getModelFromLNDatabaseThereIsParameterFVUFVM;
  }

  static GetModelFromLocalDatabaseThereIsParameterFVUFVM get getModelFromLocalDatabaseThereIsParameterFVUFVM {
    return _getModelFromLocalDatabaseThereIsParameterFVUFVM;
  }

  static GetModelFromNetworkDatabaseThereIsParameterFVUFVM get getModelFromNetworkDatabaseThereIsParameterFVUFVM {
    return _getModelFromNetworkDatabaseThereIsParameterFVUFVM;
  }

  /* End Method CallToMethodGetModelFromLNDatabaseThereIsParameterAndUseTheSettersFVUFVM */

  /* Start Method InsertModelFVUFVM */

  static InsertModelToListModelDomainForLNDatabaseFVUFVM get getInsertModelToListModelDomainForLNDatabaseFVUFVM {
    return _insertModelToListModelDomainForLNDatabaseFVUFVM;
  }

  static InsertModelToListModelDomainForLocalDatabaseFVUFVM get getInsertModelToListModelDomainForLocalDatabaseFVUFVM {
    return _insertModelToListModelDomainForLocalDatabaseFVUFVM;
  }

  static InsertModelToListModelDomainForNetworkDatabaseFVUFVM get getInsertModelToListModelDomainForNetworkDatabaseFVUFVM {
    return _insertModelToListModelDomainForNetworkDatabaseFVUFVM;
  }

  static InsertModelToLNDatabaseThereIsParameterAndInsertModelToListModelDomainForLNDatabaseFVUFVM get getInsertModelToLNDatabaseThereIsParameterAndInsertModelToListModelDomainForLNDatabaseFVUFVM {
    return _insertModelToLNDatabaseThereIsParameterAndInsertModelToListModelDomainForLNDatabaseFVUFVM;
  }

  static InsertModelToLNDatabaseThereIsParameterFVUFVM get getInsertModelToLNDatabaseThereIsParameterFVUFVM {
    return _insertModelToLNDatabaseThereIsParameterFVUFVM;
  }

  static InsertModelToLocalDatabaseThereIsParameterAndInsertModelToListModelDomainForLocalDatabaseFVUFVM get getInsertModelToLocalDatabaseThereIsParameterAndInsertModelToListModelDomainForLocalDatabaseFVUFVM {
    return _insertModelToLocalDatabaseThereIsParameterAndInsertModelToListModelDomainForLocalDatabaseFVUFVM;
  }

  static InsertModelToLocalDatabaseThereIsParameterFVUFVM get getInsertModelToLocalDatabaseThereIsParameterFVUFVM {
    return _insertModelToLocalDatabaseThereIsParameterFVUFVM;
  }

  static InsertModelToNetworkDatabaseThereIsParameterAndInsertModelToListModelDomainForNetworkDatabaseFVUFVM get getInsertModelToNetworkDatabaseThereIsParameterAndInsertModelToListModelDomainForNetworkDatabaseFVUFVM {
    return _insertModelToNetworkDatabaseThereIsParameterAndInsertModelToListModelDomainForNetworkDatabaseFVUFVM;
  }

  static InsertModelToNetworkDatabaseThereIsParameterFVUFVM get getInsertModelToNetworkDatabaseThereIsParameterFVUFVM {
    return _insertModelToNetworkDatabaseThereIsParameterFVUFVM;
  }

  /* End Method InsertModelFVUFVM */

  @protected
  void beforeCodeIsCheckTypeBaseModelDomainAndAlsoUsedFunctionSetModelDomain(
      BaseViewModel baseViewModel,
      BaseModelDomain baseModelDomain,
      Enum operation,
     )
  {
    if(baseViewModel.getTypeBaseModelDomain != baseModelDomain.runtimeType) {
      throw Exception("viewModel type baseModelDomain | not equals | type baseModelDomain. ViewModelType: ${baseViewModel.runtimeType}");
    }

    baseViewModel.setModelDomain(
        baseModelDomain,
        operation
    );
  }


}
