import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/delete_model_fvufvm/delete_model_to_list_model_domain_for_ln_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/delete_model_fvufvm/delete_model_to_list_model_domain_for_local_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/delete_model_fvufvm/delete_model_to_list_model_domain_for_network_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/delete_model_fvufvm/delete_model_to_ln_database_there_is_parameter_and_delete_model_to_list_model_domain_for_ln_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/delete_model_fvufvm/delete_model_to_ln_database_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/delete_model_fvufvm/delete_model_to_local_database_there_is_parameter_and_delete_model_to_list_model_domain_for_local_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/delete_model_fvufvm/delete_model_to_local_database_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/delete_model_fvufvm/delete_model_to_network_database_there_is_parameter_and_delete_model_to_list_model_domain_for_network_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/delete_model_fvufvm/delete_model_to_network_database_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/get_list_model_from_database_fvufvm/get_list_model_from_ln_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/get_list_model_from_database_fvufvm/get_list_model_from_local_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/get_list_model_from_database_fvufvm/get_list_model_from_network_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/get_list_model_from_database_there_is_parameter_fvufvm/get_list_model_from_ln_database_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/get_list_model_from_database_there_is_parameter_fvufvm/get_list_model_from_local_database_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/get_list_model_from_database_there_is_parameter_fvufvm/get_list_model_from_network_database_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/get_model_from_database_there_is_parameter_fvufvm/get_model_from_ln_database_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/get_model_from_database_there_is_parameter_fvufvm/get_model_from_local_database_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/get_model_from_database_there_is_parameter_fvufvm/get_model_from_network_database_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/insert_model_fvufvm/insert_model_to_list_model_domain_for_ln_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/insert_model_fvufvm/insert_model_to_list_model_domain_for_local_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/insert_model_fvufvm/insert_model_to_list_model_domain_for_network_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/insert_model_fvufvm/insert_model_to_ln_database_there_is_parameter_and_insert_model_to_list_model_domain_for_ln_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/insert_model_fvufvm/insert_model_to_ln_database_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/insert_model_fvufvm/insert_model_to_local_database_there_is_parameter_and_insert_model_to_list_model_domain_for_local_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/insert_model_fvufvm/insert_model_to_local_database_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/insert_model_fvufvm/insert_model_to_network_database_there_is_parameter_and_insert_model_to_list_model_domain_for_network_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/insert_model_fvufvm/insert_model_to_network_database_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/iterator_for_list_model_database_fvufvm/iterator_for_list_model_ln_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/iterator_for_list_model_database_fvufvm/iterator_for_list_model_local_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/iterator_for_list_model_database_fvufvm/iterator_for_list_model_network_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/model_domain_notification_fvufvm/cancel_notification_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/model_domain_notification_fvufvm/push_notification_to_show_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/model_domain_notification_fvufvm/push_notification_to_zoned_schedule_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/model_local_database_for_one_entry_fvufvm/delete_model_to_local_database_for_one_entry_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/model_local_database_for_one_entry_fvufvm/get_model_from_local_database_for_one_entry_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/model_local_database_for_one_entry_fvufvm/insert_model_to_local_database_for_one_entry_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/update_model_fvufvm/update_model_to_list_model_domain_for_ln_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/update_model_fvufvm/update_model_to_list_model_domain_for_local_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/update_model_fvufvm/update_model_to_list_model_domain_for_network_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/update_model_fvufvm/update_model_to_ln_database_there_is_parameter_and_update_model_to_list_model_domain_for_ln_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/update_model_fvufvm/update_model_to_ln_database_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/update_model_fvufvm/update_model_to_local_database_there_is_parameter_and_update_model_to_list_model_domain_for_local_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/update_model_fvufvm/update_model_to_local_database_there_is_parameter_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/update_model_fvufvm/update_model_to_network_database_there_is_parameter_and_update_model_to_list_model_domain_for_network_database_fvufvm.dart';
import 'package:library_architecture_mvvm_modify/base_function_view_using_function_view_model/extends_function_view_using_function_view_model/update_model_fvufvm/update_model_to_network_database_there_is_parameter_fvufvm.dart';

class FVUFVM {
  static final DeleteModelToLocalDatabaseForOneEntryFVUFVM _deleteModelLocalDatabaseForOneEntryFVUFVM = DeleteModelToLocalDatabaseForOneEntryFVUFVM();

  static final GetListModelFromLNDatabaseFVUFVM _getListModelFromLNDatabaseFVUFVM = GetListModelFromLNDatabaseFVUFVM();
  static final GetListModelFromLocalDatabaseFVUFVM _getListModelFromLocalDatabaseFVUFVM = GetListModelFromLocalDatabaseFVUFVM();
  static final GetListModelFromNetworkDatabaseFVUFVM _getListModelFromNetworkDatabaseFVUFVM = GetListModelFromNetworkDatabaseFVUFVM();

  static final GetModelFromLocalDatabaseForOneEntryFVUFVM _getModelFromLocalDatabaseForOneEntryFVUFVM = GetModelFromLocalDatabaseForOneEntryFVUFVM();

  static final GetListModelFromLNDatabaseThereIsParameterFVUFVM _getListModelFromLNDatabaseThereIsParameterFVUFVM = GetListModelFromLNDatabaseThereIsParameterFVUFVM();
  static final GetListModelFromLocalDatabaseThereIsParameterFVUFVM _getListModelFromLocalDatabaseThereIsParameterFVUFVM = GetListModelFromLocalDatabaseThereIsParameterFVUFVM();
  static final GetListModelFromNetworkDatabaseThereIsParameterFVUFVM _getListModelFromNetworkDatabaseThereIsParameterFVUFVM = GetListModelFromNetworkDatabaseThereIsParameterFVUFVM();

  static final GetModelFromLNDatabaseThereIsParameterFVUFVM _getModelFromLNDatabaseThereIsParameterFVUFVM = GetModelFromLNDatabaseThereIsParameterFVUFVM();
  static final GetModelFromLocalDatabaseThereIsParameterFVUFVM _getModelFromLocalDatabaseThereIsParameterFVUFVM = GetModelFromLocalDatabaseThereIsParameterFVUFVM();
  static final GetModelFromNetworkDatabaseThereIsParameterFVUFVM _getModelFromNetworkDatabaseThereIsParameterFVUFVM = GetModelFromNetworkDatabaseThereIsParameterFVUFVM();

  static final InsertModelToListModelDomainForLNDatabaseFVUFVM _insertModelToListModelDomainForLNDatabaseFVUFVM = InsertModelToListModelDomainForLNDatabaseFVUFVM();
  static final InsertModelToListModelDomainForLocalDatabaseFVUFVM _insertModelToListModelDomainForLocalDatabaseFVUFVM = InsertModelToListModelDomainForLocalDatabaseFVUFVM();
  static final InsertModelToListModelDomainForNetworkDatabaseFVUFVM _insertModelToListModelDomainForNetworkDatabaseFVUFVM = InsertModelToListModelDomainForNetworkDatabaseFVUFVM();
  static final InsertModelToLNDatabaseThereIsParameterAndInsertModelToListModelDomainForLNDatabaseFVUFVM _insertModelToLNDatabaseThereIsParameterAndInsertModelToListModelDomainForLNDatabaseFVUFVM = InsertModelToLNDatabaseThereIsParameterAndInsertModelToListModelDomainForLNDatabaseFVUFVM();
  static final InsertModelToLNDatabaseThereIsParameterFVUFVM _insertModelToLNDatabaseThereIsParameterFVUFVM = InsertModelToLNDatabaseThereIsParameterFVUFVM();
  static final InsertModelToLocalDatabaseThereIsParameterAndInsertModelToListModelDomainForLocalDatabaseFVUFVM _insertModelToLocalDatabaseThereIsParameterAndInsertModelToListModelDomainForLocalDatabaseFVUFVM = InsertModelToLocalDatabaseThereIsParameterAndInsertModelToListModelDomainForLocalDatabaseFVUFVM();
  static final InsertModelToLocalDatabaseThereIsParameterFVUFVM _insertModelToLocalDatabaseThereIsParameterFVUFVM = InsertModelToLocalDatabaseThereIsParameterFVUFVM();
  static final InsertModelToNetworkDatabaseThereIsParameterAndInsertModelToListModelDomainForNetworkDatabaseFVUFVM _insertModelToNetworkDatabaseThereIsParameterAndInsertModelToListModelDomainForNetworkDatabaseFVUFVM = InsertModelToNetworkDatabaseThereIsParameterAndInsertModelToListModelDomainForNetworkDatabaseFVUFVM();
  static final InsertModelToNetworkDatabaseThereIsParameterFVUFVM _insertModelToNetworkDatabaseThereIsParameterFVUFVM = InsertModelToNetworkDatabaseThereIsParameterFVUFVM();

  static final UpdateModelToListModelDomainForLNDatabaseFVUFVM _updateModelToListModelDomainForLNDatabaseFVUFVM = UpdateModelToListModelDomainForLNDatabaseFVUFVM();
  static final UpdateModelToListModelDomainForLocalDatabaseFVUFVM _updateModelToListModelDomainForLocalDatabaseFVUFVM = UpdateModelToListModelDomainForLocalDatabaseFVUFVM();
  static final UpdateModelToListModelDomainForNetworkDatabaseFVUFVM _updateModelToListModelDomainForNetworkDatabaseFVUFVM = UpdateModelToListModelDomainForNetworkDatabaseFVUFVM();
  static final UpdateModelToLNDatabaseThereIsParameterAndUpdateModelToListModelDomainForLNDatabaseFVUFVM _updateModelToLNDatabaseThereIsParameterAndUpdateModelToListModelDomainForLNDatabaseFVUFVM = UpdateModelToLNDatabaseThereIsParameterAndUpdateModelToListModelDomainForLNDatabaseFVUFVM();
  static final UpdateModelToLNDatabaseThereIsParameterFVUFVM _updateModelToLNDatabaseThereIsParameterFVUFVM = UpdateModelToLNDatabaseThereIsParameterFVUFVM();
  static final UpdateModelToLocalDatabaseThereIsParameterAndUpdateModelToListModelDomainForLocalDatabaseFVUFVM _updateModelToLocalDatabaseThereIsParameterAndUpdateModelToListModelDomainForLocalDatabaseFVUFVM = UpdateModelToLocalDatabaseThereIsParameterAndUpdateModelToListModelDomainForLocalDatabaseFVUFVM();
  static final UpdateModelToLocalDatabaseThereIsParameterFVUFVM _updateModelToLocalDatabaseThereIsParameterFVUFVM = UpdateModelToLocalDatabaseThereIsParameterFVUFVM();
  static final UpdateModelToNetworkDatabaseThereIsParameterAndUpdateModelToListModelDomainForNetworkDatabaseFVUFVM _updateModelToNetworkDatabaseThereIsParameterAndUpdateModelToListModelDomainForNetworkDatabaseFVUFVM = UpdateModelToNetworkDatabaseThereIsParameterAndUpdateModelToListModelDomainForNetworkDatabaseFVUFVM();
  static final UpdateModelToNetworkDatabaseThereIsParameterFVUFVM _updateModelToNetworkDatabaseThereIsParameterFVUFVM = UpdateModelToNetworkDatabaseThereIsParameterFVUFVM();

  static final DeleteModelToListModelDomainForLNDatabaseFVUFVM _deleteModelToListModelDomainForLNDatabaseFVUFVM = DeleteModelToListModelDomainForLNDatabaseFVUFVM();
  static final DeleteModelToListModelDomainForLocalDatabaseFVUFVM _deleteModelToListModelDomainForLocalDatabaseFVUFVM = DeleteModelToListModelDomainForLocalDatabaseFVUFVM();
  static final DeleteModelToListModelDomainForNetworkDatabaseFVUFVM _deleteModelToListModelDomainForNetworkDatabaseFVUFVM = DeleteModelToListModelDomainForNetworkDatabaseFVUFVM();
  static final DeleteModelToLNDatabaseThereIsParameterAndDeleteModelToListModelDomainForLNDatabaseFVUFVM _deleteModelToLNDatabaseThereIsParameterAndDeleteModelToListModelDomainForLNDatabaseFVUFVM = DeleteModelToLNDatabaseThereIsParameterAndDeleteModelToListModelDomainForLNDatabaseFVUFVM();
  static final DeleteModelToLNDatabaseThereIsParameterFVUFVM _deleteModelToLNDatabaseThereIsParameterFVUFVM = DeleteModelToLNDatabaseThereIsParameterFVUFVM();
  static final DeleteModelToLocalDatabaseThereIsParameterAndDeleteModelToListModelDomainForLocalDatabaseFVUFVM _deleteModelToLocalDatabaseThereIsParameterAndDeleteModelToListModelDomainForLocalDatabaseFVUFVM = DeleteModelToLocalDatabaseThereIsParameterAndDeleteModelToListModelDomainForLocalDatabaseFVUFVM();
  static final DeleteModelToLocalDatabaseThereIsParameterFVUFVM _deleteModelToLocalDatabaseThereIsParameterFVUFVM = DeleteModelToLocalDatabaseThereIsParameterFVUFVM();
  static final DeleteModelToNetworkDatabaseThereIsParameterAndDeleteModelToListModelDomainForNetworkDatabaseFVUFVM _deleteModelToNetworkDatabaseThereIsParameterAndDeleteModelToListModelDomainForNetworkDatabaseFVUFVM = DeleteModelToNetworkDatabaseThereIsParameterAndDeleteModelToListModelDomainForNetworkDatabaseFVUFVM();
  static final DeleteModelToNetworkDatabaseThereIsParameterFVUFVM _deleteModelToNetworkDatabaseThereIsParameterFVUFVM = DeleteModelToNetworkDatabaseThereIsParameterFVUFVM();

  static final IteratorForListModelLNDatabaseFVUFVM _iteratorForListModelLNDatabaseFVUFVM = IteratorForListModelLNDatabaseFVUFVM();
  static final IteratorForListModelLocalDatabaseFVUFVM _iteratorForListModelLocalDatabaseFVUFVM = IteratorForListModelLocalDatabaseFVUFVM();
  static final IteratorForListModelNetworkDatabaseFVUFVM _iteratorForListModelNetworkDatabaseFVUFVM = IteratorForListModelNetworkDatabaseFVUFVM();

  static final InsertModelToLocalDatabaseForOneEntryThereIsParameterFVUFVM _insertModelToLocalDatabaseForOneEntryThereIsParameterFVUFVM = InsertModelToLocalDatabaseForOneEntryThereIsParameterFVUFVM();

  static final CancelNotificationThereIsParameterFVUFVM _cancelNotificationThereIsParameterFVUFVM = CancelNotificationThereIsParameterFVUFVM();
  static final PushNotificationToShowThereIsParameterFVUFVM _pushNotificationToShowThereIsParameterFVUFVM = PushNotificationToShowThereIsParameterFVUFVM();
  static final PushNotificationToZonedScheduleThereIsParameterFVUFVM _pushNotificationToZonedScheduleThereIsParameterFVUFVM = PushNotificationToZonedScheduleThereIsParameterFVUFVM();


  /* Start Method DeleteModelLocalDatabaseForOneEntryFVUFVM */

  static DeleteModelToLocalDatabaseForOneEntryFVUFVM get deleteModelLocalDatabaseForOneEntry {
    return _deleteModelLocalDatabaseForOneEntryFVUFVM;
  }

  /* End Method DeleteModelLocalDatabaseForOneEntryFVUFVM */

  /* Start Method CallToMethodGetListModelFromLNDatabaseAndUseTheSettersFVUFVM */

  static GetListModelFromLNDatabaseFVUFVM get getListModelFromLNDatabase {
    return _getListModelFromLNDatabaseFVUFVM;
  }

  static GetListModelFromLocalDatabaseFVUFVM get getListModelFromLocalDatabase {
    return _getListModelFromLocalDatabaseFVUFVM;
  }

  static GetListModelFromNetworkDatabaseFVUFVM get getListModelFromNetworkDatabase {
    return _getListModelFromNetworkDatabaseFVUFVM;
  }

  /* End Method CallToMethodGetListModelFromLNDatabaseAndUseTheSettersFVUFVM */

  /* Start Method CallToMethodGetModelFromLocalDatabaseForOneEntryAndUseTheSettersFVUFVM */

  static GetModelFromLocalDatabaseForOneEntryFVUFVM get getModelFromLocalDatabaseForOneEntry {
    return _getModelFromLocalDatabaseForOneEntryFVUFVM;
  }

  /* End Method CallToMethodGetModelFromLocalDatabaseForOneEntryAndUseTheSettersFVUFVM*/

  /* Start Method CallToMethodGetListModelFromLNDatabaseThereIsParameterAndUseTheSettersFVUFVM */

  static GetListModelFromLNDatabaseThereIsParameterFVUFVM get getListModelFromLNDatabaseThereIsParameter {
    return _getListModelFromLNDatabaseThereIsParameterFVUFVM;
  }

  static GetListModelFromLocalDatabaseThereIsParameterFVUFVM get getListModelFromLocalDatabaseThereIsParameter {
    return _getListModelFromLocalDatabaseThereIsParameterFVUFVM;
  }

  static GetListModelFromNetworkDatabaseThereIsParameterFVUFVM get getListModelFromNetworkDatabaseThereIsParameter {
    return _getListModelFromNetworkDatabaseThereIsParameterFVUFVM;
  }

  /* End Method CallToMethodGetListModelFromLNDatabaseThereIsParameterAndUseTheSettersFVUFVM */

  /* Start Method CallToMethodGetModelFromLNDatabaseThereIsParameterAndUseTheSettersFVUFVM */

  static GetModelFromLNDatabaseThereIsParameterFVUFVM get getModelFromLNDatabaseThereIsParameter {
    return _getModelFromLNDatabaseThereIsParameterFVUFVM;
  }

  static GetModelFromLocalDatabaseThereIsParameterFVUFVM get getModelFromLocalDatabaseThereIsParameter {
    return _getModelFromLocalDatabaseThereIsParameterFVUFVM;
  }

  static GetModelFromNetworkDatabaseThereIsParameterFVUFVM get getModelFromNetworkDatabaseThereIsParameter {
    return _getModelFromNetworkDatabaseThereIsParameterFVUFVM;
  }

  /* End Method CallToMethodGetModelFromLNDatabaseThereIsParameterAndUseTheSettersFVUFVM */

  /* Start Method InsertModelFVUFVM */

  static InsertModelToListModelDomainForLNDatabaseFVUFVM get insertModelToListModelDomainForLNDatabase {
    return _insertModelToListModelDomainForLNDatabaseFVUFVM;
  }

  static InsertModelToListModelDomainForLocalDatabaseFVUFVM get insertModelToListModelDomainForLocalDatabase {
    return _insertModelToListModelDomainForLocalDatabaseFVUFVM;
  }

  static InsertModelToListModelDomainForNetworkDatabaseFVUFVM get insertModelToListModelDomainForNetworkDatabase {
    return _insertModelToListModelDomainForNetworkDatabaseFVUFVM;
  }

  static InsertModelToLNDatabaseThereIsParameterAndInsertModelToListModelDomainForLNDatabaseFVUFVM get insertModelToLNDatabaseThereIsParameterAndInsertModelToListModelDomainForLNDatabase {
    return _insertModelToLNDatabaseThereIsParameterAndInsertModelToListModelDomainForLNDatabaseFVUFVM;
  }

  static InsertModelToLNDatabaseThereIsParameterFVUFVM get insertModelToLNDatabaseThereIsParameter {
    return _insertModelToLNDatabaseThereIsParameterFVUFVM;
  }

  static InsertModelToLocalDatabaseThereIsParameterAndInsertModelToListModelDomainForLocalDatabaseFVUFVM get insertModelToLocalDatabaseThereIsParameterAndInsertModelToListModelDomainForLocalDatabase {
    return _insertModelToLocalDatabaseThereIsParameterAndInsertModelToListModelDomainForLocalDatabaseFVUFVM;
  }

  static InsertModelToLocalDatabaseThereIsParameterFVUFVM get insertModelToLocalDatabaseThereIsParameter {
    return _insertModelToLocalDatabaseThereIsParameterFVUFVM;
  }

  static InsertModelToNetworkDatabaseThereIsParameterAndInsertModelToListModelDomainForNetworkDatabaseFVUFVM get insertModelToNetworkDatabaseThereIsParameterAndInsertModelToListModelDomainForNetworkDatabase {
    return _insertModelToNetworkDatabaseThereIsParameterAndInsertModelToListModelDomainForNetworkDatabaseFVUFVM;
  }

  static InsertModelToNetworkDatabaseThereIsParameterFVUFVM get insertModelToNetworkDatabaseThereIsParameter {
    return _insertModelToNetworkDatabaseThereIsParameterFVUFVM;
  }

  /* End Method InsertModelFVUFVM */

  /* Start Method UpdateModelFVUFVM */

  static UpdateModelToListModelDomainForLNDatabaseFVUFVM get updateModelToListModelDomainForLNDatabase {
    return _updateModelToListModelDomainForLNDatabaseFVUFVM;
  }

  static UpdateModelToListModelDomainForLocalDatabaseFVUFVM get updateModelToListModelDomainForLocalDatabase {
    return _updateModelToListModelDomainForLocalDatabaseFVUFVM;
  }

  static UpdateModelToListModelDomainForNetworkDatabaseFVUFVM get updateModelToListModelDomainForNetworkDatabase {
    return _updateModelToListModelDomainForNetworkDatabaseFVUFVM;
  }

  static UpdateModelToLNDatabaseThereIsParameterAndUpdateModelToListModelDomainForLNDatabaseFVUFVM get updateModelToLNDatabaseThereIsParameterAndUpdateModelToListModelDomainForLNDatabase {
    return _updateModelToLNDatabaseThereIsParameterAndUpdateModelToListModelDomainForLNDatabaseFVUFVM;
  }

  static UpdateModelToLNDatabaseThereIsParameterFVUFVM get updateModelToLNDatabaseThereIsParameter {
    return _updateModelToLNDatabaseThereIsParameterFVUFVM;
  }

  static UpdateModelToLocalDatabaseThereIsParameterAndUpdateModelToListModelDomainForLocalDatabaseFVUFVM get updateModelToLocalDatabaseThereIsParameterAndUpdateModelToListModelDomainForLocalDatabase {
    return _updateModelToLocalDatabaseThereIsParameterAndUpdateModelToListModelDomainForLocalDatabaseFVUFVM;
  }

  static UpdateModelToLocalDatabaseThereIsParameterFVUFVM get updateModelToLocalDatabaseThereIsParameter {
    return _updateModelToLocalDatabaseThereIsParameterFVUFVM;
  }

  static UpdateModelToNetworkDatabaseThereIsParameterAndUpdateModelToListModelDomainForNetworkDatabaseFVUFVM get updateModelToNetworkDatabaseThereIsParameterAndUpdateModelToListModelDomainForNetworkDatabase {
    return _updateModelToNetworkDatabaseThereIsParameterAndUpdateModelToListModelDomainForNetworkDatabaseFVUFVM;
  }

  static UpdateModelToNetworkDatabaseThereIsParameterFVUFVM get updateModelToNetworkDatabaseThereIsParameter {
    return _updateModelToNetworkDatabaseThereIsParameterFVUFVM;
  }

  /* End Method UpdateModelFVUFVM */

  /* Start Method DeleteModelFVUFVM */

  static DeleteModelToListModelDomainForLNDatabaseFVUFVM get deleteModelToListModelDomainForLNDatabase {
    return _deleteModelToListModelDomainForLNDatabaseFVUFVM;
  }

  static DeleteModelToListModelDomainForLocalDatabaseFVUFVM get deleteModelToListModelDomainForLocalDatabase {
    return _deleteModelToListModelDomainForLocalDatabaseFVUFVM;
  }

  static DeleteModelToListModelDomainForNetworkDatabaseFVUFVM get deleteModelToListModelDomainForNetworkDatabase {
    return _deleteModelToListModelDomainForNetworkDatabaseFVUFVM;
  }

  static DeleteModelToLNDatabaseThereIsParameterAndDeleteModelToListModelDomainForLNDatabaseFVUFVM get deleteModelToLNDatabaseThereIsParameterAndDeleteModelToListModelDomainForLNDatabase {
    return _deleteModelToLNDatabaseThereIsParameterAndDeleteModelToListModelDomainForLNDatabaseFVUFVM;
  }

  static DeleteModelToLNDatabaseThereIsParameterFVUFVM get deleteModelToLNDatabaseThereIsParameter {
    return _deleteModelToLNDatabaseThereIsParameterFVUFVM;
  }

  static DeleteModelToLocalDatabaseThereIsParameterAndDeleteModelToListModelDomainForLocalDatabaseFVUFVM get deleteModelToLocalDatabaseThereIsParameterAndDeleteModelToListModelDomainForLocalDatabase {
    return _deleteModelToLocalDatabaseThereIsParameterAndDeleteModelToListModelDomainForLocalDatabaseFVUFVM;
  }

  static DeleteModelToLocalDatabaseThereIsParameterFVUFVM get deleteModelToLocalDatabaseThereIsParameter {
    return _deleteModelToLocalDatabaseThereIsParameterFVUFVM;
  }

  static DeleteModelToNetworkDatabaseThereIsParameterAndDeleteModelToListModelDomainForNetworkDatabaseFVUFVM get deleteModelToNetworkDatabaseThereIsParameterAndDeleteModelToListModelDomainForNetworkDatabase {
    return _deleteModelToNetworkDatabaseThereIsParameterAndDeleteModelToListModelDomainForNetworkDatabaseFVUFVM;
  }

  static DeleteModelToNetworkDatabaseThereIsParameterFVUFVM get deleteModelToNetworkDatabaseThereIsParameter {
    return _deleteModelToNetworkDatabaseThereIsParameterFVUFVM;
  }

  /* End Method DeleteModelFVUFVM */

  /* Start Method IteratorForListModelLNDatabaseFVUFVM */

  static IteratorForListModelLNDatabaseFVUFVM get iteratorForListModelLNDatabase {
    return _iteratorForListModelLNDatabaseFVUFVM;
  }

  static IteratorForListModelLocalDatabaseFVUFVM get iteratorForListModelLocalDatabase {
    return _iteratorForListModelLocalDatabaseFVUFVM;
  }

  static IteratorForListModelNetworkDatabaseFVUFVM get iteratorForListModelNetworkDatabase {
    return _iteratorForListModelNetworkDatabaseFVUFVM;
  }

  /* End Method IteratorForListModelLNDatabaseFVUFVM */

  /* Start Method InsertModelLocalDatabaseForOneEntryThereIsParameterFVUFVM */

  static InsertModelToLocalDatabaseForOneEntryThereIsParameterFVUFVM get insertModelToLocalDatabaseForOneEntryThereIsParameter {
    return _insertModelToLocalDatabaseForOneEntryThereIsParameterFVUFVM;
  }

  /* End Method InsertModelLocalDatabaseForOneEntryThereIsParameterFVUFVM */

  /* Start Method ModelDomainNotificationFVUFVM */

  static CancelNotificationThereIsParameterFVUFVM get cancelNotificationThereIsParameter {
    return _cancelNotificationThereIsParameterFVUFVM;
  }

  static PushNotificationToShowThereIsParameterFVUFVM get pushNotificationToShowThereIsParameter {
    return _pushNotificationToShowThereIsParameterFVUFVM;
  }

  static PushNotificationToZonedScheduleThereIsParameterFVUFVM get pushNotificationToZonedScheduleThereIsParameter {
    return _pushNotificationToZonedScheduleThereIsParameterFVUFVM;
  }

/* End Method ModelDomainNotificationFVUFVM */
}