enum EnumBaseModelDomainVM {
  all,
  insertModelToNamedDatabaseThereIsParameter,
  updateModelToNamedDatabaseThereIsParameter,
  deleteModelToNamedDatabaseThereIsParameter,
  getModelFromNamedDatabaseThereIsParameter,
  getListModelFromNamedDatabaseThereIsParameterAndNoThereIsParameter,
}