enum EnumBaseModelDomainVM {
  insertModelToNamedDatabaseThereIsParameter,
  updateModelToNamedDatabaseThereIsParameter,
  deleteModelToNamedDatabaseThereIsParameter,
  getModelFromNamedDatabaseThereIsParameter,
  getListModelFromNamedDatabaseThereIsParameterAndNoThereIsParameter,
}