enum EnumBaseListModelDomainVM {
  insertListModelToNamedDatabaseThereIsParameter,
  updateListModelToNamedDatabaseThereIsParameter,
  deleteListModelToNamedDatabaseThereIsParameter,
  getListModelFromNamedDatabaseThereIsParameterAndNoThereIsParameter,
}