enum EnumBaseListModelDomainVM {
  all,
  insertListModelToNamedDatabaseThereIsParameter,
  updateListModelToNamedDatabaseThereIsParameter,
  deleteListModelToNamedDatabaseThereIsParameter,
  getListModelFromNamedDatabaseThereIsParameterAndNoThereIsParameter,
}