enum EnumBaseTypeParameterVM {
  getModelFromNamedDatabaseParameterNamed,
  getListModelFromNamedDatabaseParameterNamed,
  updateModelToNamedDatabaseParameterNamed,
  deleteModelToNamedDatabaseParameterNamed,
  updateListModelToNamedDatabaseParameterNamed,
  deleteListModelToNamedDatabaseParameterNamed
}