import 'package:library_arch_mvvm_modify_firebase_login/model/user/ListUser.dart';
import 'package:library_arch_mvvm_modify_firebase_login/model/user/User.dart';
import 'package:library_arch_mvvm_modify_firebase_login/model/user/fbds/UpdateUserToFirebaseAuthServiceParameterLoginFBDSUsingInsertParameterRegistrationAndUpdateParameterLogin.dart';
import 'package:library_arch_mvvm_modify_firebase_login/modelQNamedServiceDataSource/userQFirebaseAuthServiceDataSource/UserQFirebaseAuthServiceDataSourceUsingInsertParameterRegistrationAndUpdateParameterLogin.dart';
import 'package:library_arch_mvvm_modify_firebase_login/modelQNamedServiceViewModel/UserQNamedServiceViewModel.dart';
import 'package:library_arch_mvvm_modify_firebase_login/utility/namedTypeParameter/LoginTypeParameter.dart';
import 'package:library_arch_mvvm_modify_firebase_login/utility/namedTypeParameter/RegistrationTypeParameter.dart';
import 'package:library_architecture_mvvm_modify/base_model/interface_clone_stream_model_for_success/i_clone_stream_model_for_success.dart';
import 'package:library_architecture_mvvm_modify/utility/base_type_parameter/bool_type_parameter.dart';

class UserQFirebaseAuthServiceViewModelUsingInsertParameterRegistrationAndUpdateParameterLogin<T extends User,Y extends ListUser>
    extends UserQNamedServiceViewModel<T,Y,UserQFirebaseAuthServiceDataSourceUsingInsertParameterRegistrationAndUpdateParameterLogin<T,Y>>
{
  UserQFirebaseAuthServiceViewModelUsingInsertParameterRegistrationAndUpdateParameterLogin(ICloneStreamModelForSuccess<T,Y> iCloneStreamModelForSuccess) : super.thereIsDataSource(UserQFirebaseAuthServiceDataSourceUsingInsertParameterRegistrationAndUpdateParameterLogin(),iCloneStreamModelForSuccess) {
    setUpdateModelToNamedServiceParameterNamedFBDS = UpdateUserToFirebaseAuthServiceParameterLoginFBDSUsingInsertParameterRegistrationAndUpdateParameterLogin();
  }

  @override
  Object thisClass() {
    return this;
  }

  Future<BoolTypeParameter?> insertUserToFirebaseAuthServiceParameterRegistration(RegistrationTypeParameter registrationTypeParameter) {
    return insertModelToNamedServiceParameterNamed<BoolTypeParameter,RegistrationTypeParameter>(registrationTypeParameter);
  }

  Future<BoolTypeParameter?> updateUserToFirebaseAuthServiceParameterLogin(LoginTypeParameter loginTypeParameter) {
    return updateModelToNamedServiceParameterNamed<BoolTypeParameter,LoginTypeParameter>(loginTypeParameter);
  }
}