import 'package:library_architecture_mvvm_modify/base_model/base_model_assistant_by_view_model_for_domain.dart';
import 'package:library_architecture_mvvm_modify/base_model/base_model_domain_for_notification.dart';

abstract class BaseModelDomainForNotificationUsingAssistantByViewModelForDomain<T extends BaseModelAssistantByViewModelForDomain>
    extends BaseModelDomainForNotification
{
  final T modelAssistantByViewModelForDomain;

  BaseModelDomainForNotificationUsingAssistantByViewModelForDomain(String uniqueId, this.modelAssistantByViewModelForDomain) : super(uniqueId);

}