import 'package:library_arch_mvvm_modify_infinite_list/utility/modelQNamedServiceListViewModelForNamedWidget/PostQJsonPlaceholderServiceAndBoolQNoServiceListViewModelForPostsListWidget.dart';
import 'package:library_architecture_mvvm_modify/utility/base_type_parameter/int_type_parameter.dart';

class PostQJsonPlaceholderServiceAndBoolQNoServiceListViewModelForPostsListWidgetTwo {
  final PostQJsonPlaceholderServiceAndBoolQNoServiceListViewModelForPostsListWidget _postQJsonPlaceholderServiceAndBoolQNoServiceListViewModelForPostsListWidget;

  PostQJsonPlaceholderServiceAndBoolQNoServiceListViewModelForPostsListWidgetTwo(this._postQJsonPlaceholderServiceAndBoolQNoServiceListViewModelForPostsListWidget);

  PostQJsonPlaceholderServiceAndBoolQNoServiceListViewModelForPostsListWidget get getPostQJsonPlaceholderServiceAndBoolQNoServiceListViewModelForPostsListWidget {
    return _postQJsonPlaceholderServiceAndBoolQNoServiceListViewModelForPostsListWidget;
  }

  Future<void> getListPostFromJsonPlaceholderServiceParameterIntAndSetListPostAndInGeneralOneTask()
  async {
    // 1
    await _postQJsonPlaceholderServiceAndBoolQNoServiceListViewModelForPostsListWidget
        .getPostQJsonPlaceholderServiceViewModelUsingGetListParameterIntForStartIndex
        .getListPostFromJsonPlaceholderServiceParameterIntAndSetListPost(IntTypeParameter(0));
    _postQJsonPlaceholderServiceAndBoolQNoServiceListViewModelForPostsListWidget
        .getPostQJsonPlaceholderServiceViewModelUsingGetListParameterIntForStartIndex
        .notifyStreamListPostUsingGetListParameterIntForStartIndex();
    return;
  }
}