import 'package:library_arch_mvvm_modify_infinite_list/utility/modelQNamedServiceListViewModelForNamedWidget/PostQHttpClientServiceAndBoolQNoServiceListViewModelForPostsListWidget.dart';
import 'package:library_architecture_mvvm_modify/utility/base_type_parameter/int_type_parameter.dart';

class PostQHttpClientServiceAndBoolQNoServiceListViewModelForPostsListWidgetTwo {
  final PostQHttpClientServiceAndBoolQNoServiceListViewModelForPostsListWidget _postQHttpClientServiceAndBoolQNoServiceListViewModelForPostsListWidget;

  PostQHttpClientServiceAndBoolQNoServiceListViewModelForPostsListWidgetTwo(this._postQHttpClientServiceAndBoolQNoServiceListViewModelForPostsListWidget);

  PostQHttpClientServiceAndBoolQNoServiceListViewModelForPostsListWidget get getPostQHttpClientServiceAndBoolQNoServiceListViewModelForPostsListWidget {
    return _postQHttpClientServiceAndBoolQNoServiceListViewModelForPostsListWidget;
  }

  Future<void> getListPostFromJsonPlaceholderServiceParameterIntAndSetListPostAndInGeneralOneTask()
  async {
    // 1
    await _postQHttpClientServiceAndBoolQNoServiceListViewModelForPostsListWidget
        .getPostQHttpClientServiceViewModelUsingGetListParameterIntForStartIndexFromJsonPlaceholder
        .getListPostFromHttpClientServiceParameterIntAndSetListPost(IntTypeParameter.success(0));
    _postQHttpClientServiceAndBoolQNoServiceListViewModelForPostsListWidget
        .getPostQHttpClientServiceViewModelUsingGetListParameterIntForStartIndexFromJsonPlaceholder
        .notifyStreamListPostUsingGetListParameterIntForStartIndexFromJsonPlaceholder();
    return;
  }
}